### ISSUE TITLE
Masonry overscanByPixels no effect

### ISSUE THREAD

**Issue by bkniffler** [bvaughn/react-virtualized#843] opened 2017-10-14 22:50 UTC
Hey, I'm using the masonry and it works great. But since I'm rendering images I'd like to take advantage of overscanByPixels to load images before the user scrolls them into viewport. As far as I understand, overscanByPixels should virtually enlarge the viewport so the images should already be loaded when I scroll to the next rows, but it doesn't. Even if I set a value like 1000, neither vertical side (top/bottom) will be loaded in advance, only when scrolled into the actual view, the images are loaded and pop up.

Is this a bug?

**Comment by bvaughn** [comment] 2017-10-15 18:09
Hm... it looks like you're right. `Masonry` uses `overscanByPixels` to [scan ahead](https://github.com/bvaughn/react-virtualized/blob/656033edec3e33c89a468643ca861625fc5ade6f/source/Masonry/Masonry.js#L176-L188) and [behind](https://github.com/bvaughn/react-virtualized/blob/656033edec3e33c89a468643ca861625fc5ade6f/source/Masonry/Masonry.js#L211-L213) _but_ looking at the DOM, I don't see any more elements being rendered if I crank up `overscanByPixels` and the [unit tests for this](https://github.com/bvaughn/react-virtualized/blob/656033edec3e33c89a468643ca861625fc5ade6f/source/Masonry/Masonry.jest.js#L162-L171) are super weak.

**Comment by bvaughn** [comment] 2017-10-15 18:17
Ah, I think this was caused by passing the position cache a negative number.

**Comment by bvaughn** [comment] 2017-10-15 18:31
Fixed in 9.11.1

**Closed by bvaughn** 2017-10-15 18:31 UTC
Labels: bug
