### ISSUE TITLE
Auto resize don't work correctly

### ISSUE THREAD

**Issue by nhducit** [bvaughn/react-virtualized#434] opened 2016-10-12 03:41 UTC
The height and width of div which contain "resize-triggers" class are correct, but the Table doesn't fulfill the container. I'm not sure this is a bug because other tables in my application work well
![screen shot 2016-10-12 at 10 37 18 am](https://cloud.githubusercontent.com/assets/4246176/19296711/01ce6a80-9068-11e6-9386-245ad0b858c1.png)

**Comment by bvaughn** [comment] 2016-10-12 05:02
Hey @nhducit. I can't really help debug this without being able to see the code and/or see the application at runtime. Even the screenshot provided doesn't have much context. 😄

The new-issue placeholder text is easy to overlook but it says basically the same thing:

---

#### _Are you reporting a bug or runtime error?_
_Setting up a test case that demonstrates a bug can be difficult and time consuming. However this can often be a huge help and time saver for me. Since I maintain this library in my spare time and without any charges, I ask that you take the time to provide me with some way of reproducing the issue you are reporting. (Videos can be helpful but in most cases I will want to actually see a live demo and view your source code.)_

_Here is a Plunker you can fork that has React Virtualized loaded and supports JSX syntax: https://plnkr.co/edit/6syKo8cx3RfoO96hXFT1_

_You may also find the online Babel tool (https://babeljs.io/repl/) quite helpful if you wish to use ES6/ES7 syntax not yet supported by the browser you are using._

---

Happy to take a look if you provide me with a repro case. In the meanwhile I'm going to close this issue since it's not really actionable for me at the moment. FWIW, `AutoSizer` has been working well for many months without any significant changes- so I assume the issue is something in the DOM ancestry of the `Table` in your screenshot. 😄

**Closed by bvaughn** 2016-10-12 05:02 UTC
