### ISSUE TITLE
List 8.6.x setting scrollTop breaks scrolling?

### ISSUE THREAD

**Issue by bhj** [bvaughn/react-virtualized#490] opened 2016-12-02 23:57 UTC
Hi, I have a List where I'm setting the initial position on mount via the scrollTop prop. Up through 8.5.3 it works fine, but with 8.6.0 and 8.6.1 no new rows are rendered while scrolling. It seems to be using the static scrollTop prop rather than the current position during a scroll when calculating which rows to render?

**Comment by bvaughn** [comment] 2016-12-03 00:13
Potentially related to the [8.6.0 release](https://github.com/bvaughn/react-virtualized/blob/master/CHANGELOG.md#860), specifically [PR #482](https://github.com/bvaughn/react-virtualized/pull/482). cc @bradchristensen, @mbrevda

**Comment by bvaughn** [comment] 2016-12-03 00:21
I'm at work still but I'll try to make time to look at this this evening. Worst case, I will revert the PR that introduced the regression and then we can work with @bradchristensen at getting it re-submitted.

**Comment by bhj** [comment] 2016-12-03 01:02
@bvaughn Have an evening :) and thanks for all your work!

**Comment by fritz-c** [comment] 2016-12-03 01:23
I had a similar issue in my [`react-sortable-tree` library at v0.1.7](https://github.com/fritz-c/react-sortable-tree/blob/v0.1.7/src/react-sortable-tree.js#L346), so if you need to reproduce, just build the example page with `npm install && npm start`.

I had apparently been setting the `scrollTop` to something at one point in time with `scrollToPixel`, but that got phased out, and the broken `<= v0.1.7` versions was just constantly passing it `scrollTop={null}`. Since this was just a programming oversight on my part, I [fixed it immediately](https://github.com/fritz-c/react-sortable-tree/commit/442f478c37df0984961f36c1785db87852aac0f4), and everything was back to normal.

**Comment by bradchristensen** [comment] 2016-12-03 01:42
The use case you have would be broken by #482, because what you're doing is setting the component to be controlled (by defining the `scrollTop` prop) and then expecting it to function in an uncontrolled way from then on (i.e. ignoring the `scrollTop` prop). With #482, a controlled Grid component will remain controlled. You should find that you can fix this on your end by keeping the `scrollTop` prop updated with the new `scrollTop` that you obtain from `onScroll`. Otherwise, to make the Grid function the way you're currently using it but without it being a controlled component, we would need to introduce a `defaultScrollTop` prop. ([relevant reading](https://facebook.github.io/react/docs/uncontrolled-components.html#default-values))

That being said though, as this is a breaking change for you and others, I think it would be wise to revert it for the 8.x release and re-release it with the next major version. Like @fritz-c mentioned, there are probably others also setting the `scrollTop` on initial mount without actually making use of it and it would be a shame for this change to break that.

**Comment by bhj** [comment] 2016-12-03 02:13
@bradchristensen thanks for the clarification and makes total sense. I'd be happy with a `defaultScrollTop` or `initialScrollTop`.

Currently I'm feeding the scrollTop value passed to my onScroll handler back to List, but with Redux in the middle because I need to persist the position in the list across life cycles. So basically there are (throttled) actions periodically updating List's scrollTop.

**Comment by bvaughn** [comment] 2016-12-03 16:02
> That being said though, as this is a breaking change for you and others, I think it would be wise to revert it for the 8.x release and re-release it with the next major version. Like @fritz-c mentioned, there are probably others also setting the `scrollTop` on initial mount without actually making use of it and it would be a shame for this change to break that.

Agreed. This sounds like the correct way forward.

I will put out a release with this change reverted.

**Comment by bvaughn** [comment] 2016-12-03 16:17
Fix released as 8.7.1.

My apologies for the error. Thank you for reporting it so quickly, @bhj. And thanks for chiming in so quickly @bradchristensen and @fritz-c.

**Closed by bvaughn** 2016-12-03 16:17 UTC
Labels: bug: unconfirmed

**Comment by mbrevda** [comment] 2016-12-04 05:45
thanks for the revert @bvaughn! @bradchristensen will you be opening another PR for the next major version with the desired changes?

**Comment by bvaughn** [comment] 2016-12-04 05:55
We can come back and reconsider this managed vs unmanaged topic in a few
months. I don't plan a major release anytime before the holidays at a
minimum. :)

**Comment by bradchristensen** [comment] 2016-12-04 07:46
Totally fine by me! Give me a cc when you're next planning a release and I'll be keen to get in there with a PR :smile:

**Comment by borisnetweb** [comment] 2019-07-24 23:22
Hi! Checking in to ask why is this closed? Don't see neither `defaultScrollTop` nor `initialScrollTop` introduced on the greed. We are using MultiGrid inside an AutoSizer and observing very buggy behaviour in version 9.21.1 - most of time it locks up scrolling if scrollTop property is passed, but then after a few runs without a reason it allows both - scrollTop to be set / updated and scrolling to function as normal. The use case is we update css classes of some of the cells based on user actions, that triggers a render and causes to loose the scroll. Tried implementing onScroll function and that just killed performance. So what it currently does is read `this.gridRef.current._bottomRightGrid.state.scrollTop` into state variable `scrollTop` that is passed as props to MultiGrid. But behaviour is inconsistent...
