### ISSUE TITLE
Fix Chrome setTimeout throttling

### ISSUE THREAD

**Issue by uglywizkid** [bvaughn/react-virtualized#722] opened 2017-07-05 14:09 UTC
Hi there.

We have faced a scrolling issue using react-virtualized table with the Chrome browser. After scrolling with the mouse wheel, we experience a quite long time of 1.5 to 2 seconds for which our web application stops responding as we would expect. However this issue does not occur when moving the scroll bar. We also experienced better performance in other browsers, e.g. Firefox.

Performance profiling in Chrome showed us, that after a scroll event the timer does not fire as expected after 150ms (how it is implemented, see DEFAULT_SCROLLING_RESET_TIME_INTERVAL in Grid.js) but after 1.5 seconds or even more.

![screenshot-1](https://user-images.githubusercontent.com/7262707/27861564-a493fc54-6181-11e7-8cd0-c1e1ceba892f.png)

We researched for an explanation and found a similar issue explained in this bug report
[https://bugs.chromium.org/p/chromium/issues/detail?id=570845](https://bugs.chromium.org/p/chromium/issues/detail?id=570845)

It seems that this is not a bug, but a feature of Chrome. 
I followed the advice at the very end of the bug report and replaced the setTimer with requestAnimationFrame and clearTimer with cancelAnimationFrame (see also my fork on [https://github.com/uglywizkid/react-virtualized/blob/master/source/Grid/Grid.js](https://github.com/uglywizkid/react-virtualized/blob/master/source/Grid/Grid.js) ). This seems to result in much better performance.

A fix in your library would be very appreciated

**Comment by bvaughn** [comment] 2017-07-05 15:43
> A fix in your library would be very appreciated

A PR would be a good start to getting said fix into RV.

**Comment by uglywizkid** [comment] 2017-07-06 08:38
Any chance you could fix your project first? Your build is failing. In this case it is hard for me to check whether my changes break other things.

**Comment by bvaughn** [comment] 2017-07-06 15:47
There's nothing to fix. Use `yarn install` for dependencies and things work fine. CI failed recently for reasons unknown. I am unable to reproduce the failure locally.

**Comment by bvaughn** [comment] 2017-07-15 16:44
CI is passing again. Upgraded Circle from Ubuntu 12 -> 14 and that seems to have resolved the test issue.

**Comment by TrySound** [comment] 2017-07-19 23:11
@uglywizkid Will this behaviour be fixed with https://github.com/bvaughn/react-virtualized/pull/742?

**Comment by giuseppepaul** [comment] 2017-08-18 19:40
Hey guys, ran into this issue too, was driving me mad so thanks for the explanation @uglywizkid

Any news on when a fix for this will be available?

**Comment by bvaughn** [comment] 2017-08-18 22:32
Fixed via #742. Will go out in the next release.

**Closed by bvaughn** 2017-08-18 22:32 UTC
