### ISSUE TITLE
Add configuration parameter to make scrollToIndex scroll to the top of a cell instead of bottom.

### ISSUE THREAD

**Issue by viniychuk** [bvaughn/react-virtualized#246] opened 2016-05-19 12:54 UTC
Hi @bvaughn,

We're using your react-virtualized to handle huge folders list with hierarchy (about 4000 folders on average) and it's working great! The only thing is that we have this issue with scrollToIndex.
When user expand a folder with a lot of subfolders we call scrollToIndex to scroll selected item to top of the list but if it's long enough it would be scrolled to it's bottom and we never see the begging of newly expanded list.

It seems you're using `getUpdatedOffsetForIndex` method from the `/utils` folder to calculate the position.  I think it would make sense to change it to scroll to the top of the cell not to the bottom of it, but if you think otherwise – can you somehow make it configurable?
Appreciate your advise on this.

**Comment by bvaughn** [comment] 2016-05-19 13:46
Hi @viniychuk,

This feature was designed to scroll the minimal amount possible in order to ensure that a cell was fully visible. I think that behavior is still generally the best.

For example, if a row is partially visible at the bottom of a list and you scroll it into view, the list will only shift down enough to ensure that the row is fully visible. It would be more jarring if the list scrolled so the target row was at the top (I think).

I believe what you're asking for is similar to optional `alignToTop` parameter of [`Element.scrollIntoView`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView). Seems reasonable maybe as an additional, optional `scrollBehavior` prop that could be "auto", "top", or "bottom".

I'll leave this issue open for when I have a bit of time to spend on it. Feel free to contribute a PR in the meanwhile if you'd like. :)

**Comment by viniychuk** [comment] 2016-05-19 13:57
Thanks for the response, I'll try to find the best approach and will update with what we've got.

**Comment by bvaughn** [comment] 2016-05-19 14:09
Actually thinking about this a few more seconds~ `Grid` has 2 scroll-to properties, `scrollToColumn` and `scrollToRow`. I think adding a 3rd property `scrollBehavior` that is an enum ("start", "end", "auto" - defaulting to "auto") is a reasonable approach for exposing this functionality to users.

I said "top" and "bottom" initially because I was only thinking of vertical scrolling but I think we should follow flexbox approach on this and use axis-agnostic terms.

**Comment by bvaughn** [comment] 2016-05-22 19:05
I'm picking this up by the way.

**Comment by bvaughn** [comment] 2016-05-22 20:18
This feature has been released as version 7.1.0. `Collection`, `Grid`, `FlexTable`, and `VirtualScroll` all now expose a new property, `scrollToAlignment`. This defaults to "auto" (previous behavior) but can be changed to "start" or "end" to control the alignment of scrolled-to rows and columns.

**Closed by bvaughn** 2016-05-22 20:18 UTC
Labels: enhancement

**Comment by viniychuk** [comment] 2016-05-23 18:19
Thanks it works perfectly!
