### ISSUE TITLE
Scroll glitches/artifacts in Firefox 46+ on Windows

### ISSUE THREAD

**Issue by cyberxndr** [bvaughn/react-virtualized#251] opened 2016-05-22 12:05 UTC
Hi, @bvaughn. There is a scroll issue in a new firefox release. Scroll glitches appears in result of 45 to 46 upgrade. Please, check the following example:

https://cdn.rawgit.com/cyberxndr/9ef19845ef538293bbd4ccd6a9701929/raw/eea41df6ab3056bb3061ddfb70d876d52d7e0c13/example.html (linux, firefox 46.0.1)

Here is a webm:
http://webmshare.com/57QLb (base example)
http://webmshare.com/MnPJj (real-world example)

It's probably related to the new firefox 46 scrolling system (something with backround-color fulfillment when rows is preloaded after the scroll, can't say more atm). I've tried some workarounds, and found at least two ways to fix this behaviour:
1)`.Grid { will-change: auto !important;  }` (have no idea what will break in this case)
2)`.FlexTable__row {  background-color: white;` (not a good solution for the styling reasons)

I'm not sure how this should be fixed (if it would). Hope the workarounds will be helpful.

**Comment by bvaughn** [comment] 2016-05-22 17:45
Hey @cyberxndr,

Thanks for the detailed write-up. You didn't mention which version of react-virtualized you're using. From a quick inspection of your example source, I'd guess 6.x. So I'm curious...do you have any idea if Firefox 46 shows this same behavior with 7.x (the latest release)? I'd check myself but I'm unable to reproduce the behavior shown in your video using the example you've linked. (I'm running Firefox 46.0.1 on OS X 10.11.4.)

**Comment by cyberxndr** [comment] 2016-05-22 18:11
6.x is used for the example, but 7.x had the same behavior (I don't found compiled js for 7.x, so I got the old one). I can also confirm that bug exists in the firefox 46.0.1, runned on windows 7.

**Comment by bvaughn** [comment] 2016-05-22 18:21
> I don't found compiled js for 7.x, so I got the old one

7.x UMD build is available on npmcdn and cndjs. (And on NPM of course).

**Comment by cyberxndr** [comment] 2016-05-22 18:40
There is an updated example with 7.0.5 https://cdn.rawgit.com/cyberxndr/63d07a939582fbbceb75c9bb6c209f35/raw/96b1fe4c3de62c4c86ab5eedd59d321a0882d011/example.html

**Comment by bvaughn** [comment] 2016-05-22 20:21
Thanks for the updated example. As expected, I'm still unable to reproduce the behavior (on my Mac). I don't have access to a Windows 7 machine at the moment but I'll try to find one. In the meanwhile I have reached out on Twitter to see if James Long has any ideas or pointers about what may be going wrong. (I'm not sure what's up, to be honest.)

**Comment by bvaughn** [comment] 2016-05-23 04:28
Spoke with James Long about this briefly and he believes the fact that it occurs on Windows only indicates that it's likely a Firefox bug. Fortunately you filed a fantastic bug report and so I've basically just transferred it over to Mozilla's bug tool: https://bugzilla.mozilla.org/show_bug.cgi?id=1274894

I'll keep you posted if I hear anything more. :)

**Comment by cyberxndr** [comment] 2016-05-23 05:04
It's a good news!

There is one thing to notice: the bug applies not only to Windows, but both Windows and Linux. I got it on Linux generally, and only confirmed for Windows later. Maybe this detail will be useful.

**Comment by bvaughn** [comment] 2016-05-23 05:08
Interesting. Could you add a comment to the Bugzilla issue?

**Comment by cyberxndr** [comment] 2016-05-23 05:14
Definetely

**Comment by bvaughn** [comment] 2016-05-23 05:16
Thank you! :)

**Comment by bvaughn** [comment] 2016-05-31 15:38
Looks like the Mozilla team has picked up this issue and tagged it as "confirmed" on their end so I'm going to close the react-virtualized bug for now. We'll re-open if needed!

**Closed by bvaughn** 2016-05-31 15:38 UTC
Labels: bug, help wanted

**Comment by bvaughn** [comment] 2016-05-31 15:53
Actually @cyberxndr, Mozilla says they _can_ reproduce it on 46 but _can't_ on nightly, 47, or 48 so they think the issue has since been fixed. They're asking me to verify (but I was never able to reproduce it on OSX in the first place). Can you take a look? :)

**Comment by cyberxndr** [comment] 2016-05-31 19:07
Nice to see its fixed from their side. I already dropped an answer. It works well.

Thanks for participation :)

**Comment by bvaughn** [comment] 2016-05-31 19:20
No problem. Stoked to see they've already fixed it. :)
