### ISSUE TITLE
Collection Example scrolling has bug

### ISSUE THREAD

**Issue by liximomo** [bvaughn/react-virtualized#315] opened 2016-07-20 06:04 UTC
[Collection Example](https://bvaughn.github.io/react-virtualized/?component=Collection) when set Num Cells at exact 10000, it automatically scrolls to top when scroll to bottom. Maybe there are other magic numbers except 10000.
Environment:  mac Chrome

**Comment by bvaughn** [comment] 2016-07-20 06:15
Can you post a video of this or something? I can't reproduce what you're describing.

**Comment by liximomo** [comment] 2016-07-20 07:48
@bvaughn ![collection](https://cloud.githubusercontent.com/assets/9816225/16978992/64d53938-4e91-11e6-8f32-96dec0ae692b.gif)

**Comment by bvaughn** [comment] 2016-07-20 07:58
What browser?

**Comment by bvaughn** [comment] 2016-07-20 07:58
(and version)

**Comment by liximomo** [comment] 2016-07-20 09:44
chrome 51.0.2704.103 (64-bit)

**Comment by liximomo** [comment] 2016-07-20 09:48
And i just upgrade to 51.0.2704.106, still has the problem.

**Comment by bvaughn** [comment] 2016-07-20 10:26
Ah, I can reproduce it now. Not sure why I couldn't at first.

**Comment by bvaughn** [comment] 2016-08-02 04:03
Heh heh. So I got around to looking at this tonight (finally). It's kind of a silly bug. There's a bit of randomness to it (which may explain why I couldn't reproduce it at first). But it basically comes down to these lines: https://github.com/bvaughn/react-virtualized/blob/master/source/Collection/CollectionView.js#L353-L369

What's happening is that- as you scroll to the bottom, children become sparser. It might be possible to scroll down so far that no children are visible for the horizontal slice you're viewing- even though some exist elsewhere along the collection. In this case, the no-content renderer kicks in (which is a bug) which causes the `scrollTop` to be reset, which immediately causes children to become visible again.

This is a logic bug from too closely copying `Grid`. (Its children are checkerboard, so this sparseness problem isn't an issue there.)

**Comment by bvaughn** [comment] 2016-08-02 04:16
Resolved by commit 7fba44a and fixed in release [`7.17.1`](https://github.com/bvaughn/react-virtualized/blob/master/CHANGELOG.md#7171).

Thanks for bringing this to my attention. Good eye. :)

**Closed by bvaughn** 2016-08-02 04:16 UTC
Labels: bug
