### ISSUE TITLE
TypeError: invalid 'instanceof' operand this._autoSizer.parentNode.ownerDocument.defaultView.HTMLElement

### ISSUE THREAD

**Issue by achtan** [bvaughn/react-virtualized#960] opened 2018-01-09 10:02 UTC
hi in Firefox i'm getting this error 
````
TypeError: invalid 'instanceof' operand this._autoSizer.parentNode.ownerDocument.defaultView.HTMLElement
````

**Edit:**
ahother error:
````
NullError: _this._detectElementResize is undefined

STACKTRACE:
WindowScroller/_this._unregisterResizeListener@....
````

all fine in chrome... 

@version: 9.16.1

**Comment by ahutchings** [comment] 2018-01-09 12:46
Hi @achtan. What version of Firefox are you seeing this in?

**Comment by achtan** [comment] 2018-01-09 12:47
MAC 
FF: 57.0 (64-bit)

**Comment by ahutchings** [comment] 2018-01-09 13:04
I am not able to reproduce the issue here with the same FF version, but I'm guessing we need another null check on the right hand side of the instanceof test. Are you able to pause on that exception and see which part of `this._autoSizer.parentNode.ownerDocument.defaultView.HTMLElement` is null or undefined?

Alternatively, would you be able to post a minimal example that reproduces the issue on CodeSandbox or a similar site?

**Comment by borm** [comment] 2018-01-09 17:05
I also have problem with scroller in latest FF for mac os, problem with property `scrollElement`, on first time it is, then it is window

**Comment by bvaughn** [comment] 2018-01-13 22:00
Hi @achtan 👋 This bug report does not actually list any steps to reproduce. Where are you seeing this error? What do you do (if anything) to trigger it? I am also running OSX with Firefox 57.0.4 (64-bit) and I don't see this bug on the demo page. Does that mean you're seeing it elsewhere?

> Are you able to pause on that exception and see which part of `this._autoSizer.parentNode.ownerDocument.defaultView.HTMLElement` is null or undefined?

I don't think it would be `ownerDocument`. That should only be null [if the `parentNode` itself is the `document`](https://developer.mozilla.org/en-US/docs/Web/API/Node/ownerDocument).

Are we talking about SSR here? (That would be an important detail to have been omitted.) If so though, it could be the `defaultView`? The [documentation says](https://developer.mozilla.org/en-US/docs/Web/API/Document/defaultView):
> In browsers, `document.defaultView` returns the `window` object associated with a document, or `null` if none is available.

I'll add a null check to cover this potential case (dc3c7ce). Beyond that, I'm going to close this issue because it isn't actionable. If it's still happening in 9.17 (going out shortly) then please provide information about how to actually reproduce it. 😄

**Closed by bvaughn** 2018-01-13 22:00 UTC
