### ISSUE TITLE
InfiniteLoader, how could I get current range?

### ISSUE THREAD

**Issue by Sigura** [bvaughn/react-virtualized#198] opened 2016-04-20 15:13 UTC
Hello,

first, thank you for you wonderful work!

Just a question, my case with InfiniteLoader:
1. scroll to any positon
2. click to sort of any column
3. reset list to empty

then load happen, but only with previous range of loading, without isRowLoaded calls.
then ~half of screen is still empty

react-virtualized 6.0.7

questions:
1. how I could now current visible range
2. or What I could do to call isRowLoaded for current view
?

**Comment by bvaughn** [comment] 2016-04-20 16:16
Hey @Sigura,

It's much easier for me if you can share a Plunker (or even a fork of react-virtualized) demonstrating your problem. That way I can look at the code and see what's happening. Any chance you can do that?

Also, it probably doesn't hurt to update to the latest release considering it's backwards compatible with what you're running. That way we can at least rule out any bugfixes that may have happened since then.

**Comment by Sigura** [comment] 2016-04-20 16:21
@bvaughn it's not so easy to make a sample. And I really could not undestand why you do not understand case.

Anyway:
* I could not use lattest release I have a lot of dependancies to React 0.14.8
* I found workaround: scrollToIndex=0 + manaly change range to 0-50

**Comment by bvaughn** [comment] 2016-04-20 16:37
@Sigura I get asked a lot of questions about this library. I try to help answer every one. This takes a decent amount of time (my personal time, not time I'm being paid for). So in return I often ask for people to take the time to create an example of the bug they're reporting because (a) it makes things easier on me to reproduce and identify a problem and (b) it rules out simple mistakes that a user is sometimes making (when it's not actually a bug). I feel this is a pretty reasonable request.

The latest release of React Virtualized [supports both React 0.14.x and 15.x](https://github.com/bvaughn/react-virtualized/blob/master/package.json#L141) so I'm not sure I understand your reasoning with regard to your version of React.

**Comment by Sigura** [comment] 2016-04-20 17:03
@bvaughn
> I'm not sure I understand your reasoning with regard to your version of React.
hm... I got a lot of errors why I tried to install latest. Ok, I will try again.

Understandable. As I said thank you for your wonderful work.

Please, don't worry. I will try to update and then I will try to reproduce issue.

If case will reproduced... anyway don't worry.

**Comment by bvaughn** [comment] 2016-04-20 17:47
No worries. Thank you. :)

I'm going to close this issue for the time being since you've found a workaround. If you are still able to reproduce the issue and are willing to share a Plunkr (or something similar, even a fork of react-virtualized like I said) with me then I'll reopen it and take a look.

**Closed by bvaughn** 2016-04-20 17:47 UTC
Labels: question
