### ISSUE TITLE
headerRenderer receives wrong dataKey when the column changes its dataKey

### ISSUE THREAD

**Issue by bgerm** [bvaughn/react-virtualized#288] opened 2016-06-21 20:56 UTC
I'm using 7.8.3 and am trying to introduce responsive columns, such that a different set appear depending on the width we get from AutoSizer.  I ran into an issue where the headerRenderer was receiving the wrong dataKey after the column of the same index switched to a different column type (when the width changed).

I had to change this: 

      <div
        {...a11yProps}
        key={`Header-Col${columnIndex}`}
        className={classNames}
        style={style}
      >
        {renderedHeader}
      </div>

to this:

      <div
        {...a11yProps}
        key={`Header-Col${dataKey}`}
        className={classNames}
        style={style}
      >
        {renderedHeader}
      </div>

**Comment by bvaughn** [comment] 2016-06-22 01:56
Can you provide a reproduction case?

For instance, the `FlexTable` demo: https://bvaughn.github.io/react-virtualized/?component=FlexTable

If you click the "hide column?" checkbox, the headers and columns are updated.

**Comment by bvaughn** [comment] 2016-06-22 02:02
I just updated my test project locally to swap columns and confirmed that it seems to be working as expected. The `headerRenderer` is invoked with the updated/correct `dataKey`.

The only possible source of confusion I see is that...unless some external prop changes (eg `rowCount`) the table rows won't be automatically updated. This is because react-virtualized components are _pure_ (they don't update unless their properties change). You can tell the `FlexTable` to update via the [`forceUpdategrid` method](https://github.com/bvaughn/react-virtualized/blob/master/docs/FlexTable.md#forceupdategrid) though if you'd like.

**Comment by bvaughn** [comment] 2016-06-22 02:06
Actually it looks like your source of confusion may be the parameters. Check out [the docs for `headerRenderer`](https://github.com/bvaughn/react-virtualized/blob/master/docs/FlexColumn.md#headerrenderer). It does not receive a `columnIndex` parameter.

Going to close this for now as it doesn't seem to be a bug (at least not one I can reproduce). Please let me know if you have any questions though! Or if I misunderstood something, please provide me with a reproduction case on Plunkr~ 

Here is a Plunker you can fork that has React Virtualized loaded and supports JSX syntax: https://plnkr.co/edit/6syKo8cx3RfoO96hXFT1

**Closed by bvaughn** 2016-06-22 02:06 UTC
Labels: bug: unconfirmed

**Comment by bgerm** [comment] 2016-06-22 15:28
Hi Brian,

Sorry for the confusion.  The code snippet I provided was from `_createHeader` of FlexTable.js (https://github.com/bvaughn/react-virtualized/blob/master/source/FlexTable/FlexTable.js#L416).

I created a demo app that tries to make use of dynamic columns w/ column filtering (https://github.com/bgerm/flextable-filter-sort/).  To give an example of the bug, if you run the demo in a large resolution you will see the VERB column.  Enter in some text to filter on that column.  Then resize the browser until the columns change.  In that same column position you will see the filter text still appear, but for a different dataKey (though the label has changed).  

A better example is if you you add `verb: 'foo'` to this line:  https://github.com/bgerm/flextable-filter-sort/blob/master/src/App.js#L19.  It  won't show foo under the verb column.  This is because that column has the dataKey of "created" since that was rendered in the third column position first, which is now occupied by verb.

I hope I didn't make that too confusing.

**Comment by bvaughn** [comment] 2016-06-22 23:14
No worries. Thanks for the extra info and the reproduction case.

If I add logging to your `renderHeader` method like so...
```js
console.log('renderHeader():', dataKey)
```
Then when ther are 4 columns I see:
```
renderHeader(): name
renderHeader(): stateLabel
renderHeader(): verb
renderHeader(): favoritesLabel
```
And when I resize it so that only 3 show, I see:
```
renderHeader(): name
renderHeader(): stateLabel
renderHeader(): created
```
So the correct `dataKey` is being passed to the header.

The problem seems to be that your `FilterHeader` component is using `defaultValue` instead of `value` for the input. And when `filterDisabled` is true (as it is for the 3rd column when you've resized) it's not calling `getFilterMap` to update the value and so the previous, unmanaged value is still there.


This can be confirmed by adding logging to the `getFilterMap` method. For 4 columns I see:
```
getFilterMap() name Object {favoritesLabel: "trans", verb: "f"}
getFilterMap() stateLabel Object {favoritesLabel: "trans", verb: "f"}
getFilterMap() verb Object {favoritesLabel: "trans", verb: "f"}
getFilterMap() favoritesLabel Object {favoritesLabel: "trans", verb: "f"}
```
But when I resize to 3 columns I only see 2 logs:
```
getFilterMap() name Object {favoritesLabel: "trans", verb: "f"}
getFilterMap() stateLabel Object {favoritesLabel: "trans", verb: "f"}
```

**Comment by bgerm** [comment] 2016-06-22 23:57
Thanks a lot for taking the time to go through the code.  I still think there may be a key reconciliation issue.

Since the width is initially 0, the third column starts out as "created" and then becomes "verb" (assuming large resolution).  If in the constructor of FilterHeader you add `this.state = { ..., dataKey: props.dataKey };` and then in the render you have `console.log('dataKey', this.state.dataKey, this.props.dataKey)`  you will see `created verb`.  

The example is slightly more complicated than it needs to be, but I just wanted to show how I was using it.  I am struggling to come up with a way to make this example work without modifying the FlexTable code (which may not be the best solution).

**Comment by bvaughn** [comment] 2016-06-23 00:01
If you want to update your example so that it reproduces the problem you're referring to, I'll take another look.

**Comment by bgerm** [comment] 2016-06-23 00:22
Cool.  Made the update.

**Comment by bvaughn** [comment] 2016-06-23 01:59
`FilterHeader` seems to have a bit of a React anti-pattern going on. The `dataKey` in `state` is set only once, in the constructor, based on the _initial_ `props` value. But when the value in `props` changes (as the component is re-rendered) the `state` value gets out of sync.

You can see this happening by adding the following to `FilterHeader`:
```js
  componentWillReceiveProps (nextProps) {
    console.log('<FilterHeader> componentWillReceiveProps() dataKey:', nextProps.dataKey)
  }
```

Now console will log...
```
<FilterHeader> componentWillReceiveProps() dataKey: verb
rendering dataKey --> created verb
^^^^^^ mismatch ^^^^^^^^^^^
```

**Comment by bvaughn** [comment] 2016-06-23 02:01
Still pretty sure `FlexTable` is doing the correct thing here.

If your components have `state` that is dependent in any way on `props`, be sure to use [the `componentWillReceiveProps` lifecycle method](https://facebook.github.io/react/docs/component-specs.html) to update `state` accordingly. (Or better yet, just drive everything off of `props` if you're able and avoid the potential pitfall.)
