### ISSUE TITLE
Uncaught Invariant Violation: Maximum update depth exceeded.

### ISSUE THREAD

**Issue by Brighter209** [bvaughn/react-virtualized#1381] opened 2019-05-29 11:22 UTC
## Bug
Hi everyone, I'm using react-virtualized with CellMeasurer like this:

https://codesandbox.io/s/reactvirtualized-list-with-random-height-kn2if

On chrome I have this error when I'm trying to render my list, but everything works fine on firefox

![image](https://user-images.githubusercontent.com/7300656/58553088-49c33f00-8214-11e9-9169-6f0942674db8.png)

thank you,

### Version
|                   |          |
|-------------------|----------|
| Browser           |  chrome, firefox        |
| OS                |  win10        |
| React             |   16.4.1       |
| React DOM         |    16.4.1      |
| react-virtualized |    9.21.1      |

**Comment by wuweiweiwu** [comment] 2019-05-30 07:59
I tink its linked to #1375

**Comment by Brighter209** [comment] 2019-05-31 10:56
Thanks, revert to 9.21.0 seems to fix my issue.

**Comment by Brighter209** [comment] 2019-05-31 16:17
Hi, sorry my issue isn't solve, I though it was but when I reverted to 9.21.0 and test it. I first tried with a small amount of items to render (50) and then tried to render 3000 items and it worked.

But when I tried to render 3000 items first I had the error I mentioned in my previous post

**Comment by wuweiweiwu** [comment] 2019-06-04 08:36
duplicate of #1375

**Closed by wuweiweiwu** 2019-06-04 08:36 UTC
Labels: duplicate
