### ISSUE TITLE
Duplicate declaration "bpfrpt_prototype_Scroll"

### ISSUE THREAD

**Issue by kentcdodds** [bvaughn/react-virtualized#993] opened 2018-01-31 17:36 UTC
# Reporting a Bug?

The built es version of https://unpkg.com/react-virtualized@9.18.4/dist/es/List/List.js has a duplicate declaration of a named import. You can see it at the bottom of the file:

```js
import { bpfrpt_proptype_Scroll } from '../Grid';
// ...
import { bpfrpt_proptype_Scroll } from './types';
```

Found this gives me an error in storybook/webpack:

```
info @storybook/react v3.3.11
info 
info => Loading custom .babelrc
info => Loading custom addons config.
info => Using default webpack setup based on "Create React App".
info Building storybook ...
ERR! Failed to build the storybook
ERR! ./stories/node_modules/react-virtualized/dist/es/List/List.js
ERR! Module build failed: Duplicate declaration "bpfrpt_proptype_Scroll"
ERR! 
ERR!   360 | import { bpfrpt_proptype_RowRenderer } from './types';
ERR!   361 | import { bpfrpt_proptype_RenderedRows } from './types';
ERR! > 362 | import { bpfrpt_proptype_Scroll } from './types';
ERR!       |          ^
ERR!   363 | import PropTypes from 'prop-types';
ERR! 
ERR! BabelLoaderError: Duplicate declaration "bpfrpt_proptype_Scroll"
ERR! 
ERR!   360 | import { bpfrpt_proptype_RowRenderer } from './types';
ERR!   361 | import { bpfrpt_proptype_RenderedRows } from './types';
ERR! > 362 | import { bpfrpt_proptype_Scroll } from './types';
ERR!       |          ^
ERR!   363 | import PropTypes from 'prop-types';
ERR! 
ERR!     at transpile (/Users/kdodds/Desktop/downshift/node_modules/babel-loader/lib/index.js:65:13)
ERR!     at /Users/kdodds/Desktop/downshift/node_modules/babel-loader/lib/fs-cache.js:118:18
ERR!     at ReadFileContext.callback (/Users/kdodds/Desktop/downshift/node_modules/babel-loader/lib/fs-cache.js:31:21)
ERR!     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
ERR!  @ ./stories/node_modules/react-virtualized/dist/es/List/index.js 8:12-29
ERR!  @ ./stories/node_modules/react-virtualized/dist/es/index.js
ERR!  @ ./stories/examples/windowing-with-react-virtualized.js
ERR!  @ ./stories/config.js
ERR!  @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./stories/config.js
```

I'm not sure how this happened. I looked at the source code and I don't know where those declarations are coming from... 🤔

**Comment by kentcdodds** [comment] 2018-01-31 17:37
I should note that this only started happening in the last few hours. So I'm guessing it's related to this change: https://github.com/bvaughn/react-virtualized/commit/61733411d80552e140eaa1a3f82f76d94eb70b98

Specifically this in the `.babelrc` probably:

```diff
-        ["flow-react-proptypes", { "deadCode": true }],
+        ["flow-react-proptypes", { "deadCode": true, "useESModules": true }],
```

**Comment by reinaldoarrosi** [comment] 2018-01-31 17:44
I've also encountered this issue when bundling code with webpack.

Also, when bundling code with browserify I get `Uncaught ReferenceError: bpfrpt_proptype_ScrollIndices is not defined`

**Comment by vieron** [comment] 2018-01-31 18:31
Duplicate of #990 #991

**Comment by TrySound** [comment] 2018-01-31 18:34
Related to https://github.com/brigand/babel-plugin-flow-react-proptypes/issues/176
Until that you may stick to 9.18.0

**Comment by bvaughn** [comment] 2018-01-31 20:28
Can you npm-deprecate the bad version @TrySound ? So this doesn't cause people pain

**Comment by bvaughn** [comment] 2018-01-31 20:29
(And also publish a fixed version in the meanwhile. It doesn't seem super reasonable to hope that people will stick with 9.18.0

**Comment by TrySound** [comment] 2018-01-31 21:33
@bvaughn Reverted changes to 9.18.0. Deprecated broken releases. Published 0.18.5. I guess we need to build examples from built files to catch such gotchas.

Sorry for broken releases, guys.

**Closed** 2018-01-31 21:33 UTC

**Comment by kentcdodds** [comment] 2018-01-31 21:34
Some of my libraries have some post-build tests to make sure things are output as I expect: https://github.com/paypal/downshift/blob/master/other/misc-tests/__tests__/build.js

**Comment by barbalex** [comment] 2018-01-31 21:35
Shit happens. Thanks A LOT for engaging in this great project!

**Comment by bvaughn** [comment] 2018-01-31 22:19
Thank you for being so on top of this, @TrySound .
