### ISSUE TITLE
Width/Height NaN for AutoSizer

### ISSUE THREAD

**Issue by kloy** [bvaughn/react-virtualized#150] opened 2016-03-09 23:53 UTC
When following the example for https://github.com/bvaughn/react-virtualized/blob/master/docs/AutoSizer.md I get NaN for width and height inbetween the initial values of 0 and the final values of the browser window. Component fails with an exception of `Invalid size returned for cell 0 of value NaN`.

Using Chrome 48.

**Comment by bvaughn** [comment] 2016-03-10 01:57
Works for me: http://jsbin.com/kapesovaci/1/edit?html,css,js,output

Please provide more context?

**Comment by bvaughn** [comment] 2016-03-11 04:13
Going to close as "cannot reproduce" for now since I can't. Please give me more information if you'd like and maybe I can help. :)

**Comment by edulan** [comment] 2016-04-29 12:11
We've experienced the same issue while mounting and unmounting components very fast. We think the issue may be related to `getComputedStyle` call used in `_onResize` callback:

```javascript
const style = getComputedStyle(document.createElement('div'));
style.paddingLeft;
// ""
```

And then when calculating `paddingLeft` parsing fails evaluating an empty string, which results in `NaN`:

```javascript
const paddingLeft = parseInt(style.paddingLeft, 10);
// NaN
```

This only happens on an element that's not been added yet to DOM. What do you think @bvaughn?

cc @andresgutgon

**Comment by andresgutgon** [comment] 2016-04-29 13:03
This method:
https://github.com/bvaughn/react-virtualized/blob/master/source/AutoSizer/AutoSizer.js#L93

**Comment by bvaughn** [comment] 2016-04-29 15:10
> This only happens on an element that's not been added yet to DOM.

Ah, that's tricky... the `_onResize` method is only called from within `componentDidMount`, which I assumed meant it was mounted. But you're seeing it rendered and then not mounted (presumably because a parent component causes a state-change/unmount)?

I guess we could add a check there.

**Comment by andresgutgon** [comment] 2016-04-29 15:12
Thanks @bvaughn 👏

**Comment by bvaughn** [comment] 2016-04-29 22:56
Should be fixed via release 6.3.1. Please let me know if you're still seeing it, @andresgutgon and @edulan

**Closed by bvaughn** 2016-04-29 22:56 UTC
Labels: bug

**Comment by edulan** [comment] 2016-05-02 10:03
Wow, thanks for your super fast response @bvaughn :clap:

Your fix seems to be working great, but we're now facing this error:

```
Uncaught TypeError: Cannot read property 'firstElementChild' of undefined
```

while evaluating [this](https://github.com/bvaughn/react-virtualized/blob/master/source/vendor/detectElementResize.js#L39). Somehow `__resizeTriggers__` is set to `false` value.

This bug seems totally unrelated with react-virtualized and it's more a javascript-detect-element-resize one. Couldn't find any issue related with this in their repo, so I'll open a new one

Thanks for your help!

**Comment by jontewks** [comment] 2017-02-22 21:36
I'm seeing @edulan's error as well. I also see that the javascript-detect-element-resize was forked and modified and stored in `/vendor`, so it seems like the issue should be open here rather than on that package that appears to have been abandoned.

**Comment by bvaughn** [comment] 2017-02-22 22:02
Forked and modified here for performance reasons. Have never seen the error mentioned above though. If you can find a repro case or would be interested in submitting a fix though- I'd welcome either!

**Comment by jontewks** [comment] 2017-02-22 22:06
@bvaughn I'll try to make a minimal repro case later on and then I'll take a shot at resolving it. I can repro consistently in our production app only on IE and Edge when adding or removing a row.

**Comment by 2Steaks** [comment] 2017-10-30 15:15
I got this error, though it was the AutoSizer but it turned out I was missing rowCount from the Table component. Maybe some improved error handling around unpopulated mandatory fields?

**Comment by bvaughn** [comment] 2017-10-30 16:22
> Maybe some improved error handling around unpopulated mandatory fields?

Beyond what `PropTypes` provide? You should already see the following errors in dev mode:

> Warning: Failed prop type: The prop `rowCount` is marked as required in `Table`, but its value is `undefined`.
    in Table (created by AutoSizer)
    in AutoSizer (created by YourComponentHere)
    ...
