### ISSUE TITLE
Data Cell gets misaligned after horizontal scroll

### ISSUE THREAD

**Issue by pkumar84** [bvaughn/react-virtualized#255] opened 2016-05-25 16:16 UTC
Dear Developer,
I have 50-60 columns and 1000s of rows. all looks good once data get loaded but somehow data-cell gets misaligned as soon i do horizontal scroll, Attached is screenshot. Once i inspect column div and row cell div, both have same "left" value,

It gets aligned as soon as i scroll all the way to left. somehow it gets break on right horizontal scroll. 

Note : this issue happens only when scrollbar reaches all the way to right.

```
 <ScrollSync>
            {({onScroll, scrollLeft}) =>
               <div className="col flex-1">
                  <AutoSizer disableHeight>
                     {({width}) =>
                        <Grid onSectionRendered={({columnStartIndex, columnStopIndex}) => this.onSectionRendered(columnStartIndex, columnStopIndex)} ref={(sefRef) => this.setColumnDataGrid(sefRef)} className="overflow-hidden" height={39} rowHeight={39} columnsCount={columnList.size + 1} rowsCount={1} {...{scrollLeft, width, columnWidth}} renderCell={renderHeader}/>
                     }
                  </AutoSizer>
                  <div className="flex-1">
                     <AutoSizer>
                        {({width, height}) =>
                           <Grid ref={(sefRef) => this.setTableDataGrid(sefRef)} rowHeight={30} columnsCount={columnList.size + 1} rowsCount={data.length === 0 ? 1 : data.length} {...{onScroll, scrollLeft, width, height, renderCell, columnWidth}}/>
                        }
                     </AutoSizer>
                  </div>
               </div>
            }
         </ScrollSync>
```

Any advise ? 
![screen shot 2016-05-25 at 12 07 57 pm](https://cloud.githubusercontent.com/assets/12733539/15547602/7b0c50ba-2272-11e6-99e1-09a93cb63f1b.png)

**Comment by bvaughn** [comment] 2016-05-25 16:38
Hey @pkumar84,

Please point me at a Plunker (or similar) where I can see this happening and I'll be happy to take a look.

Consider forking one of these playground files for an easy starting point: https://github.com/bvaughn/react-virtualized/tree/master/playground

**Comment by pkumar84** [comment] 2016-05-25 18:32
sure, will try to do so, thanks. Another question, is there any way we can highlight the entire row on Grid ?

**Comment by bvaughn** [comment] 2016-05-25 18:44
There's a recipe for this:
Demo: https://rawgit.com/bvaughn/react-virtualized/master/playground/hover.html
Source: https://github.com/bvaughn/react-virtualized/blob/master/playground/hover.js

**Comment by pkumar84** [comment] 2016-05-25 19:04
cool, thanks .

**Comment by bvaughn** [comment] 2016-05-27 16:21
Gentle reminder. :)

**Comment by bvaughn** [comment] 2016-05-28 14:53
I'm going to close this for now since it's not actionable for me without having more information (a way to reproduce the behavior). I'll still see comments though- so when you get something put together, add it here and I'll take a look and re-open the issue if necessary. :)

**Closed by bvaughn** 2016-05-28 14:53 UTC
Labels: more info needed

**Comment by pkumar84** [comment] 2016-06-02 13:19
Sorry for late response @bvaughn, we fixed this problem, problem was if we have horizontal scroll bar and add extra 15px (vertical scrollBar width) to last column width, it fixed the issue. Not sure it will help you or not to narrow down the issue. kindly advise.

**Comment by bvaughn** [comment] 2016-06-02 14:08
Glad you found a solution for it.

I would still need a reproduction case before I can advise. Let me know if you take the time to create one and I'll look at it. :)

**Comment by pkumar84** [comment] 2016-06-10 18:02
Sure, will try. thnx.
