### ISSUE TITLE
Possible issue with measureAllCells when rowCount === fixedRowCount in MultiGrid

### ISSUE THREAD

**Issue by kachkaev** [bvaughn/react-virtualized#555] opened 2017-01-27 17:38 UTC
I just caught this exception in an edge case:

```
CellSizeAndPositionManager.js:66 Uncaught (in promise) Error: Requested index -1 is outside of range 0..0
    at CellSizeAndPositionManager.getSizeAndPositionOfCell (CellSizeAndPositionManager.js:66)
    at ScalingCellSizeAndPositionManager.getSizeAndPositionOfCell (ScalingCellSizeAndPositionManager.js:85)
    at Grid.measureAllCells (Grid.js:133)
    at MultiGrid.measureAllCells (MultiGrid.js:72)
```

This happened in a `MultiGrid` when a number of fixed rows (or columns) ended up equal to the number of rows (or columns) total. This situation took place when I had no data to show in the grid, so it just consisted of one (top-left) blank cell.

Looks like the issue originates [from `Grid`](https://github.com/bvaughn/react-virtualized/blob/38ba7879177dfdd8ceae66f169991d0aadf5dc78/source/Grid/Grid.js#L254-L259):
```
      this._columnSizeAndPositionManager.getSizeAndPositionOfCell(columnCount - 1);
      this._rowSizeAndPositionManager.getSizeAndPositionOfCell(rowCount - 1);
```

When the main (scrollable) grid inside `MultiGrid` has 0 rows or columns, the methods receive `-1` and throw.

Hope the explanation is clear without MWE - sorry for not providing it. I'll be happy to report this in better detail if needed.

**Comment by bvaughn** [comment] 2017-01-28 07:08
Fixed in 8.11.3

**Closed by bvaughn** 2017-01-28 07:08 UTC

**Comment by thibaultvdb-incerta** [comment] 2019-03-19 11:41
@bvaughn Is this still fixed in version 9.20.0?
I'm using multigrid with a fixed header so "fixedRowCount" = 1 but when I use our "CellRangeRenderer" function it complains with following error message:

![image](https://user-images.githubusercontent.com/46312962/54603301-42c5c680-4a44-11e9-8b71-e8a38d1d1e87.png)

**Comment by alex-pominov** [comment] 2022-01-13 15:01
The issue is still in 9.22.3.

**Comment by JuhQ** [comment] 2024-06-20 09:04
I am also seeing this issue in 9.22.3.

**Comment by v1rg1le** [comment] 2025-06-25 15:58
Still seeing this in 9.22.6
