### ISSUE TITLE
React 16 beta: findDOMNode return null

### ISSUE THREAD

**Issue by mrasoahaingo** [bvaughn/react-virtualized#762] opened 2017-07-27 09:09 UTC
Hi!

![image](https://user-images.githubusercontent.com/12088397/28662987-61b51f20-72bc-11e7-87e6-e209c74f9670.png)

Since i updated to the new version beta of react and react-dom, CellMeasurer.js is broken at this point:
```
var node = (0, _reactDom.findDOMNode)(this);
```
![image](https://user-images.githubusercontent.com/12088397/28663483-c81248d2-72bd-11e7-838f-71075bec1d20.png)

where node is null
Is there something i am doing wrong?
```
      <CellMeasurer
        cache={this.cache}
        columnIndex={0}
        key={key}
        parent={parent}
        rowIndex={index}
      >
        {({ measure }) => (
          <div ... />
        )}
      </CellMeasurer>
```
Thanks!

**Comment by mrasoahaingo** [comment] 2017-07-27 13:34
Seems to work after upgrading to v9.9.0.
Now i have another error when i need to measure() the child of a list

![image](https://user-images.githubusercontent.com/12088397/28672798-06deeab6-72e1-11e7-81b4-212aabad1b35.png)

`
      <CellMeasurer
        cache={this.cache}
        columnIndex={0}
        key={key}
        parent={parent}
        rowIndex={index}
      >
        {({ measure }) => (
          <div
            style={style}
            ref={() => { measure(); }}
          >
            item
          </div>
        )}
      </CellMeasurer>
`

:(

**Comment by bvaughn** [comment] 2017-07-27 16:13
> Seems to work after upgrading to v9.9.0.

Yes, old version so react-virtualized that were released before the React 16 alpha will not support 16 b'c of the breaking changes to render into subtree. I think version 8 is the oldest version that supports 16 but I'm not sure. It's probably best to update to the latest versions of libs like this when updating a major dependency like React though. 😄 

As for the `measure` thing you mention, the [react-virtualized demo site](https://bvaughn.github.io/react-virtualized/) has been running on an alpha version of React 16 for a couple of months now, which includes using the `measure` param passed by `CellMeasurer` (source code [here](https://github.com/bvaughn/react-virtualized/blob/master/source/CellMeasurer/CellMeasurer.DynamicHeightList.example.js)). I don't see the issue you've shown in a screenshot, so it's not as easy to reproduce as just using `CellMeasurer`.

Provide a repro of this and I'll look into it. Maybe it's an RV bug. Maybe it's a React bug. Maybe it's something you're doing in your application. I have no way to know at the moment since I only have a code snippet and a screenshot.

**Comment by bvaughn** [comment] 2017-07-27 16:15
I'm going to close this issue now since (a) the original issue reported only applies to versions of RV that pre-dated React 16 alpha and (b) the secondary issue needs a repro case before I can proceed since I'm not able to repro it on my end. (The [live site](https://bvaughn.github.io/react-virtualized/#/components/CellMeasurer) is using React 16 + `CellMeasurer` without any problems.)

**Closed by bvaughn** 2017-07-27 16:15 UTC
