### ISSUE TITLE
Add API to configure a cell's overflow CSS

### ISSUE THREAD

**Issue by crzrcn** [bvaughn/react-virtualized#26] opened 2015-12-15 00:47 UTC
A cell's content is clipped by [truncatedColumnText](https://github.com/bvaughn/react-virtualized/blob/e04a01e9641037e939114b4eb7bbc3eca2056d87/source/FlexTable/FlexTable.js#L189) and there is no API to prevent this.

Current behavior:
<img width="91" alt="screen shot 2015-12-14 at 4 44 59 pm" src="https://cloud.githubusercontent.com/assets/1812608/11798696/13a702e6-a282-11e5-8b9f-853411d7eadd.png">

Expected behavior:
<img width="94" alt="screen shot 2015-12-14 at 4 45 39 pm" src="https://cloud.githubusercontent.com/assets/1812608/11798700/2551e24a-a282-11e5-84bd-8c886253a9c5.png">

**Comment by bvaughn** [comment] 2015-12-15 03:34
Thanks for reporting this @crzrcn. Good eye. :) I'll see if I can fix it in a patch release.

**Comment by bvaughn** [comment] 2015-12-15 03:48
Hm. I wonder if this is a font metrics issues. I'm not seeing this behavior locally.

Can you give me some more information (browser, version, font family/size, etc.)

**Comment by crzrcn** [comment] 2015-12-15 18:09
Browser: Chromium 43, Chrome 47, Firefox 40-42.
Font family: Roboto, 'Open Sans', sans-serif
Font size: 14px
Font weight: normal

**Comment by bvaughn** [comment] 2015-12-17 19:08
Note to self: we chatted about this and I think the fix is to change the inner `overflow: hidden` to `overflow: visible` so that certain `line-height` values won't clip the text. Need to experiment a bit and make sure this is a safe change but I think it should be.

**Comment by bvaughn** [comment] 2015-12-17 22:36
I think... after further examination... that this issue is being caused by a project-specific style (not something in react-virtualized). I believe if you remove the `line-height: 1` style then things should work as expected (no clipping).

Looks like [most browsers use a default `line-height` of around `1.2`](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height) depending on the font-family.

**Comment by bvaughn** [comment] 2015-12-17 22:37
I'm going to close this issue as working-as-intended unless I hear differently.

**Closed by bvaughn** 2015-12-17 22:37 UTC
Labels: bug
