### ISSUE TITLE
MultiGrid falls out of sync when scrolling

### ISSUE THREAD

**Issue by OleksandrNechai** [bvaughn/react-virtualized#971] opened 2018-01-16 19:41 UTC
When scroll (with a scroll wheel on the mouse, Windows 10, Chrome, Edge, Firefox) during a very short period of time parts of MultiGrid are out of syn, then they get back to sync.

This is how it looks like irrespective of the size of the grid: 
![](https://i.stack.imgur.com/w971w.gif)

Here is a screenshot of this moment when main data grid and it's fixed part are out of sync: 
![](https://i.stack.imgur.com/a7EwL.png)

Here the [CodePen ](https://codepen.io/anon/pen/opMPeK) to reproduce.

**Comment by bvaughn** [comment] 2018-01-17 03:29
This looks like a duplicate of #647 and #291. Check out my responses to those issues ([like this one](https://github.com/bvaughn/react-virtualized/issues/647#issuecomment-292397805)).

I don't think there's anything `react-virtualized` can do about this, short of moving everything in the the UI thread (like `fixed-data-table` does) but this incurs a very serious cost of making scrolling feel jumpy and unresponsive if rendering and layout takes longer than the 16ms window, [as described here](https://github.com/bvaughn/react-virtualized/issues/647#issuecomment-292397805). (The decision to use async, "scroll" event was a conscious one from the start for this project.)

There are some techniques that you could try (discussed on #291) to force the event handling to be sync for your synced grids, if you'd like. I haven't tried them myself so I can't vouch for them.

I always welcome PRs to improve performance and developer experience for `react-virtualized`, and fresh eyes often have new ideas- so I'd welcome you to contribute if you have ideas for ways to improve this. As it is though, I think this issue is "working as designed" (for the reasons mentioned above).

**Closed by bvaughn** 2018-01-17 03:29 UTC

**Comment by OleksandrNechai** [comment] 2018-01-17 08:09
Brian, thanks a lot for this project and nice fast response to this issue. And sorry for duplication, I have tried to avoid that but failed :-). 

I have checked out [fixed-data-table](http://schrodinger.github.io/fixed-data-table-2/fixed-right-columns.html)  and it scrolls very well for me. So just out of curiosity, is this performance penalty for using UI thread for scrolling only noticeable when cells have a complex and slow layout to render? If so, why not have a prop which controls whether to use/not use UI thread? I am very new to web front-end world, sorry if my question is stupid :-).

**Comment by bvaughn** [comment] 2018-01-17 15:57
No worries. It's hard when there are hundreds of issues. I have trouble deduping myself sometimes, and I've seen them all before.

> So just out of curiosity, is this performance penalty for using UI thread for scrolling only noticeable when cells have a complex and slow layout to render?

Yes-ish. This will vary based on the specs of the computer running it, how much work it is to render the cells, what else is being done at that time in the page (eg other JavaScript and rendering), etc.

> If so, why not have a prop which controls whether to use/not use UI thread?

Complexity! 😄  I don't want to build two implementations.

PS. No worries. It's not at all a stupid question.

**Comment by wtfil** [comment] 2018-08-09 13:58
@OleksandrNechai
I found the solution for Chrome. It looks like browser optimization rather than solution, but still, it works fine 

on root node of your component you have to add this css
```css
#example::after {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    pointer-events: none;
}
```

Going to dig into rendering theory and found solutions for other browsers and I can make PR if I am lucky

**Comment by OleksandrNechai** [comment] 2018-08-09 14:12
@wtfil , thank you very much for looking at this problem :-) It still bugs me. My users, however, do not complain yet :-)

**Comment by tuchk4** [comment] 2018-09-24 22:19
@wtfil nice workaround. Scroll is really synced but for some reason this solution makes grid slow to be slow. But synced with fixed columns and rows :)

@bvaughn I have question about fixed columns / rows feature.
Maybe for simple cases (1 fixed row / 1 fixed column)  don't need to render multiple Grids?
Always render cells:
- fixed row ( _rowIndex=0_) and all it's columns. Provide style where top === Grid.scrollTop
- fixed column (each rowIndex, _columnIndex=0_). Provide style where left === Grid.scrollLeft


It should be very simple in runtime and without scroll sync problems because there is nothing to sync.

**Comment by tuchk4** [comment] 2018-09-25 00:10
I made some experiments

- this solution with `position: absolute` will not work because of `_debounceScrollEnded();`. Fixed columns will be scrolled out and then appear again on scroll end.
- It is possible to implement only if set them as `position: sticky` but as I understand this way is not stable :(

**Comment by aiingstan** [comment] 2018-12-02 16:35
> I made some experiments
> 
> * this solution with `position: absolute` will not work because of `_debounceScrollEnded();`. Fixed columns will be scrolled out and then appear again on scroll end.
> * It is possible to implement only if set them as `position: sticky` but as I understand this way is not stable :(

I did exactly those 2 things today and had almost the same conclusions with you!
Can you share with me how do you use the `position: sticky` way to make the left column be fixed? I found that if cells inside the left column are scrolled out of the window they'll be cleared?

As for me, I plan to append 2 inside the outter div to achieve something like this [CodePen Demo](https://codepen.io/aiingstan/pen/MzLZZw)

**Comment by wtfil** [comment] 2018-12-02 17:07
@tuchk4 The problem with async scroll is not something directly related to the `react-virtualized`, but rather browser internal rendering algorithms.  Despite the fact that columns might looks like they have different `scrollTop` while rapid scrolling, the browser will keep them the same, but render asynchronously.
I guess my "trick" tells browser to render entire box as the single unit, so it does. However, this does not work in FF and on Windows, so this is definitely not the best fix

**Comment by dasler-fw** [comment] 2023-11-03 07:21
> @OleksandrNechai I found the solution for Chrome. It looks like browser optimization rather than solution, but still, it works fine
> 
> on root node of your component you have to add this css
> 
> ```css
> #example::after {
>     content: '';
>     position: absolute;
>     top: 0;
>     left: 0;
>     width: 100%;
>     height: 100%;
>     pointer-events: none;
> }
> ```
> 
> Going to dig into rendering theory and found solutions for other browsers and I can make PR if I am lucky

only working solution. thank you
