### ISSUE TITLE
Issue with Collection scrolling when data is loaded async

### ISSUE THREAD

**Issue by garylesueur** [bvaughn/react-virtualized#525] opened 2017-01-04 15:57 UTC
https://plnkr.co/edit/81aoXFH8mkZhoxaKib2o

So first off, I've setup a plunker as requested. This is a snippet of what we are/were planning to use in production.

As it stands, the grid works as desired. When we started using real data, we came across a big problem.

To see the issue, on script.jsx - line 45, if you comment out the initial "this.populate()" then you can see the entire grid / page scrolling rather than just the items as desired.

At the moment I am cheating by seeding the grid with initial data but I'd like to not do this.

Thanks.

**Comment by bvaughn** [comment] 2017-01-04 17:11
Thank you for the Plnkr and the detailed bug description. Looks like this bug can be reproduced on the official site as well: https://bvaughn.github.io/react-virtualized/#/components/Collection

1. Open page
1. Change cell count to 0
1. Change cell count back to 1000

The problem seems to be that the `overflow: auto` style is not present as of step 3. But logging the `style` object shows that I'm specifying that style... I'm a bit confused.

**Comment by bvaughn** [comment] 2017-01-04 17:16
Interesting... [these lines](https://github.com/bvaughn/react-virtualized/blob/master/source/Collection/CollectionView.js#L365-L375) are forcefully turning off scrollbars if the content is not tall or wide enough to require scrolling.

It seems like- once I've set a value for `overflowX: hidden` then subsequently applying a style with `overflow: auto` (and no `overflowX` property at all) doesn't stick.

This seems like a bug outside of react-virtualized.

I can fix it in react-virtualized though by making `CollectionView` styles [do what `Grid` does](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.js#L537-L547).

**Comment by bvaughn** [comment] 2017-01-04 17:26
Fixed with b5b8e29. Will go out in a release sometime in the next couple of days.

In the meanwhile you should be able to work around this on your end by passing a `style` prop like:

```jsx
<Collection
  {...props}
  style={{
    overflowX: 'auto',
    overflowY: 'auto'
  }}
/>
```

**Closed by bvaughn** 2017-01-04 17:26 UTC

**Comment by bvaughn** [comment] 2017-01-04 23:30
I've captured this bug with a small Plnkr: https://plnkr.co/edit/7O1xZUqbD13ST2BAxcm9?p=preview

I'll see if I can track it down if it's a React bug.

**Comment by bvaughn** [comment] 2017-01-05 17:17
The underlying bug actually impacts all [shorthand CSS properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties). Turns out that shorthand properties aren't [fully?] supported by React due to [how the style updates are currently done](https://github.com/facebook/react/issues/8689#issuecomment-270527957). I was unaware of this.

Either way, it's been fixed in react-virtualized for now and the fix will roll out with the next release.

**Comment by garylesueur** [comment] 2017-01-05 17:54
Superb, thanks for that. Just been reading up and I don't feel so bad about not solving it myself now 👍

Build failing btw

**Comment by bvaughn** [comment] 2017-01-05 18:00
Build is failing in CI because PhantomJS is crashing in the middle of tests:
![screen shot 2017-01-05 at 10 00 15 am](https://cloud.githubusercontent.com/assets/29597/21691530/cc790e22-d32d-11e6-81a0-a797bdcbf04a.png)

I haven't had the time to look into it yet. It doesn't crash for me locally. (All tests pass.) If you have the time to look into it, I'd love a hand. Otherwise I'll get to it eventually.
