### ISSUE TITLE
Rendering problems for Grid with big amount of rows

### ISSUE THREAD

**Issue by martinpesout** [bvaughn/react-virtualized#576] opened 2017-02-13 12:45 UTC
Hi, in the past there was a problem with rendering in Grid with 40k+ rows (https://github.com/bvaughn/react-virtualized/issues/524). I've found that there is still some problem with this Grid.

Steps to reproduce:

* Problem is visible on Grid with more rows. It works for table with 10000 rows. It doesn't work for table with 40000 rows.
* Problem is visible in Chrome (reproduce on Mac devices and on Linux, even when using magic mouse and also on normal mouse with scrollwheel). Than we will have to do many times quick scrolling down and up.

You can reproduce it on your example https://bvaughn.github.io/react-virtualized/#/components/Grid with 40000 rows.

You will get this problem: 

![snimek obrazovky 2017-02-13 v 13 32 31](https://cloud.githubusercontent.com/assets/239468/22883885/88a7c6c8-f1f2-11e6-9056-5f33cc81c301.png)

![uno-13-2017 13-35-03](https://cloud.githubusercontent.com/assets/239468/22883894/8d66b9b2-f1f2-11e6-8e83-1bcc962c4825.gif)

**Comment by benjaminjs** [comment] 2017-02-13 16:44
I'm having the same issue exactly. Using a table and the infinite load. I have a million row count, but 10,000 works fine.

<img width="1043" alt="screen shot 2017-02-13 at 10 41 34 am" src="https://cloud.githubusercontent.com/assets/2501984/22892768/4a8e75a8-f1d9-11e6-818b-06b9f909ba3a.png">

**Comment by bvaughn** [comment] 2017-02-14 00:52
Hm. I'm unable to reproduce this myself (using Chrome 56.0.2924.87, macOS 10.12.3) on the demo site. I just cranked up the demo to 400,000 rows at 30px height each (12M pixels total) and mouse and scrollbar scrolling seem fine.

**Comment by johnhaley81** [comment] 2017-02-14 01:02
@martinpesout does it flicker if you use the scroll bar to scroll?

**Comment by bvaughn** [comment] 2017-02-14 01:07
To be clear- the above video I attached shows trackpad flinging, scrollbar dragging, and arrow key scrolling as well. All 3 seem fine to me.

**Comment by benjaminjs** [comment] 2017-02-14 01:09
It only happens at the very top.

**Comment by bvaughn** [comment] 2017-02-14 01:12
> It only happens at the very top.

Ah! That's helpful. I see it now.

**Comment by bvaughn** [comment] 2017-02-14 01:50
I believe I have a fix 😄

**Comment by bvaughn** [comment] 2017-02-14 02:16
Fixed by commit e78036a. Will go out with version 9 (see PR #577)

**Closed by bvaughn** 2017-02-14 02:16 UTC
Labels: more info needed

**Comment by martinpesout** [comment] 2017-02-14 08:43
Sorry for later response. I'm in different timezone 😄  but confirmed. I also had this problem at the top of huge Grids. If I'll move to the middle I cannot reproduce it.

I see that fix is here. Thanks a lot.
