### ISSUE TITLE
Unresolved Peer-Dependency with React 17

### ISSUE THREAD

**Issue by cileria** [bvaughn/react-virtualized#1715] opened 2021-12-23 13:01 UTC
## Bug Report

$ npm install

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: webtools-app@1.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   dev react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.3.0 || ^16.0.0-alpha" from react-virtualized@9.22.3
npm ERR! node_modules/react-virtualized
npm ERR!   dev react-virtualized@"^9.21.9" from the root project

### What is the current behavior?

React 17 is out now since quite a while and the required React 15+ or React 16 Alpha are really old now. Still, react-virtualized requires to have them installed.

### What is the expected behavior?

No peer dependency issues with React 17.

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?
|                   |          |
|-------------------|----------|
| Browser           |     Chrome newest   |
| OS                |   Windows 10 Enteprise       |
| React             |    17.0.2    |
| React DOM         |     17.0.2     |
| react-virtualized |    9.22.3      |

**Comment by ax0n-pr1me** [comment] 2021-12-28 22:18
Duplicate of #1711

**Comment by cileria** [comment] 2022-01-12 09:18
Any news?

**Comment by bvaughn** [comment] 2023-04-09 13:37
Version 9.22.4 has been published with peer dependencies updated to include React 17 and 18. (No other changes from 9.22.3)

https://github.com/bvaughn/react-virtualized/releases/tag/v9.22.4

**Closed by bvaughn** 2023-04-09 13:37 UTC
