### ISSUE TITLE
Scrolling goes past the component internal state and the rendering is offset

### ISSUE THREAD

**Issue by ivanfryda** [bvaughn/react-virtualized#308] opened 2016-07-08 12:24 UTC
I'm using VirtualScroll and I set the rowHeight as 26.5 px. Every scroll goes 53 px down, which means 2 rows. I'm debugging the onScroll and onRowsRendered values and that works OK. Past the 10th row, the scroll is still going down 53px down, but the scroll goes down 4 rows instead of 2. This is also the time the overscanStartIndex starts being more than zero. This is making the component render previous rows, and newer rows are just a blank space.

Do you have any ideas why this might be happening?

**Comment by bvaughn** [comment] 2016-07-08 13:43
> This is making the component render previous rows, and newer rows are just a blank space.

This behavior often indicates that a user forgot to include the react-virtualized stylesheet.

```js
// Make sure to import default styles.
// This only needs to be done once; probably during your application's bootstrapping process.
import 'react-virtualized/styles.css';
```

If that's not the cause, I'll have to see your project to be able to provide additional insight.

**Comment by ivanfryda** [comment] 2016-07-08 13:50
I have that stylesheet included in my source file. Is there any way I can confirm that this is really working?

**Comment by bvaughn** [comment] 2016-07-08 14:00
Look for the CSS class `.Grid` or `.Grid__cell` in your bundled CSS to confirm it's being included successfully I guess. :)

Let me know when you have something I can take a look at.

**Comment by bvaughn** [comment] 2016-07-10 22:47
Going to close this issue for now since I'm pretty sure the issue isn't in react-virtualized. But I could be wrong- in which case I'll keep watching for comments and re-open the issue. :)

Might help if you could provide me a Plunker or something so I can see what's happening.

**Comment by bvaughn** [comment] 2016-07-10 22:48
Here is a Plunker you can fork that has React Virtualized loaded and supports JSX syntax: https://plnkr.co/edit/6syKo8cx3RfoO96hXFT1

**Closed by bvaughn** 2016-07-10 22:47 UTC
Labels: more info needed

**Comment by ivanfryda** [comment] 2016-07-11 09:44
Thanks, I'm trying to reproduce the bug there.

Do you know how to include react-addons-shallow-compare in Plunker? I'm using react-virtualized 7.12.1 (with React and  react-addons-shallow-compare 15.1.0).

**Comment by ivanfryda** [comment] 2016-07-11 10:15
Forget about my last post, it seems the css in not being included in the bundle. Is there anything else I should consider? I'm including that same line in the initial jsx file.

**Comment by ivanfryda** [comment] 2016-07-11 10:29
Fixed it. I didn't have style-loader.

**Comment by bvaughn** [comment] 2016-07-11 12:49
Glad to hear you've fixed it! :)
