### ISSUE TITLE
ArrowKeyStepper: inconsistency in vertical and horizontal scroll to keep (or not) the selected cell visible

### ISSUE THREAD

**Issue by gillesdandrea** [bvaughn/react-virtualized#828] opened 2017-09-28 14:45 UTC
**Step to reproduce:**
- Go to: https://bvaughn.github.io/react-virtualized/#/components/ArrowKeyStepper
- Try to scroll right, it's blocked to ensure the selected cell visible
- Try to scroll to down, selected cell may become out of sight.

**What happens**
There is an inconsistency between horizontal and vertical scrolling to keep (or not) the selected cell visible. IMHO, scroll should always be possible even if it makes the selected cell out of sight.

**Comment by bvaughn** [comment] 2017-10-14 18:21
> Try to scroll right, it's blocked to ensure the selected cell visible

This is actually a bug, reported via #816, not intentional behavior.

Closing as a duplicate of #816 for now.

**Closed by bvaughn** 2017-10-14 18:21 UTC
