### ISSUE TITLE
will-change on .Grid causes fixed divs inside of virtualscroll to behave oddly 

### ISSUE THREAD

**Issue by BossGrand** [bvaughn/react-virtualized#318] opened 2016-07-21 22:23 UTC
Hey guys I have a modal for each element in my virutal scroll list and I noticed that after adding in VirtualScroll it was making my modal look like 

<img width="1440" alt="screen shot 2016-07-21 at 3 19 38 pm" src="https://cloud.githubusercontent.com/assets/2106699/17040778/93f38150-4f56-11e6-82c4-7e33c564c454.png">

i found out that removing will-change from the .Grid I got it to behave like it should
<img width="1440" alt="screen shot 2016-07-21 at 3 21 09 pm" src="https://cloud.githubusercontent.com/assets/2106699/17040823/c97b4934-4f56-11e6-80dd-d2c1ddc1662e.png">

**Comment by bvaughn** [comment] 2016-07-21 22:32
I'm not really sure what I'm looking at. I assume you're using some sort of portal component to parent your modal overlay _outside of_ the `Grid`? I don't immediately know why a `Grid` CSS property would cause any sizing change like what you're reporting.

Going to need to see a Plunkr reproducing this in order to help. I don't have enough info. :)

**Comment by BossGrand** [comment] 2016-07-21 22:34
I think this is more of a bug with will-change.

My modal is actually inside the grid which is whats causing the issue. 
What does a portal component look like?

**Comment by bvaughn** [comment] 2016-07-21 22:58
I don't think [`will-change`](https://developer.mozilla.org/en/docs/Web/CSS/will-change) is supposed to have the kind of effect you're talking about. I think it's more likely the `overflow: auto` setting is what's causing your modal overlay to be clipped.

But unless you can point me at a Plunkr or a similar reproduction, I can't help.

By "portal" I meant something like [`react-portal`](https://github.com/tajo/react-portal). This type of component lifts UI from its parent container to the root so it can overlay the whole body safely. Without this, an `overflow` property of any parent can clip the contents to keep them "within" the parent.

**Comment by BossGrand** [comment] 2016-07-21 23:03
Yea just found react portal, I'lll try to get you an example. I wrote this to bring it to your attention but thinking about it further I don't really think there is anything you can do about it. 

I know for sure that will-change has something to do with it because when I remove it my fixed div acts as it should. I went through every css one by one toggling them to find out what was happening.

Also thank you for pointing me to react-portal!

**Comment by bvaughn** [comment] 2016-07-21 23:58
Hm. Interesting.

Well you can always override default `Grid` styling using either the `style` or `className` props- so there's always that option if you want to disable the `will-change` optimization. :)

I'm going to close this issue for now because I don't think there's any action I can take but if you want to share a reproduction with me I'll be happy to look and make suggestions! :)

For what it's worth, I use portals for modals like that to avoid things like this (or similar z-index stacking issues). It's probably a good idea to do _anyway_. :)

**Closed by bvaughn** 2016-07-21 23:58 UTC
Labels: more info needed

**Comment by ClementParis016** [comment] 2019-01-15 15:03
Hey, I encountered the same issue and it's actually a normal behaviour of `will-change`: https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#Identifying_the_containing_block

It creates a new containing block which indeed makes `position: fixed` relative to it instead of the viewport.

Rendering the element in a React portal should actually do the trick ;)
