### ISSUE TITLE
List flashing when scrolling

### ISSUE THREAD

**Issue by kramarmm** [bvaughn/react-virtualized#718] opened 2017-07-03 08:49 UTC
Hi. What I can do with this problem?

Code:
<List
          height={window.innerHeight - 156}
          rowCount={reviews.length}
          rowRenderer={this.rowRenderer}
          width={720}
          className={'rewiews-list'}
          rowHeight={80}
          sortBy={() => {
            this.makeSort();
            this.list.forceUpdate();
          }}
 />

![jul-03-2017 11-45-10](https://user-images.githubusercontent.com/25547238/27785140-527a38b8-5fe5-11e7-9825-3b4f46561ca2.gif)

**Comment by bvaughn** [comment] 2017-07-03 15:28
It helps a lot of this sort of issue is filed as a repro case (in Webpackbin or Plnkr) rather than a partial code snippet and a gif. I have very little visibility into what could be going wrong at the moment.

I would say that your `sortBy` prop looks fishy. You're passing a function, which will change each time render is called, which would bypass any smart `shouldComponentUpdate` checks- although I don't think that would be the cause of what your image shows.

As it is, this issue isn't really answerable, so I'm closing this issue. If you can provide a repro case I'll take a look. 😄

**Closed by bvaughn** 2017-07-03 15:28 UTC

**Comment by Hongbo-Miao** [comment] 2018-01-03 09:49
Hi @kramarmm did you figure out what causing your issue? Thanks
(Met same issue, and I don't have `sortBy`)

**Comment by kramarmm** [comment] 2018-01-03 10:22
I'm using `CellMeasurer` and `CellMeasurerCache`
**in constructor:**
`    this._cache = new CellMeasurerCache({
      fixedWidth: true,
      keyMapper: rowIndex => `${uniqueKey}`,
    });
`

and then, if your row height or width, will be depended on props - rewrite cache **in componentWillReceiveProps:**
`
componentWillReceiveProps() {
    this._cache = new CellMeasurerCache({
      fixedWidth: true,
      keyMapper: rowIndex => `${uniqueKey}`,
    });
  }
`

**Comment by Hongbo-Miao** [comment] 2018-01-03 10:39
Thanks for response, @kramarmm !
Seems something else causing my issue, I will post back once I found the issue.
I am still new to this package. Need more time to learn.

**Comment by sslgeorge** [comment] 2018-04-27 08:38
I think this issue is genuine, I am also using it and having same issue, I have over 10K records in my list

**Comment by vjeranc** [comment] 2018-05-12 22:03
The virtualized list rerenders on every 1px scroll. Given that you are creating all of the elements from scratch on every scroll, you have to be careful to not rerender the inner parts of the tree, so that diff stays fast. If diff is wrong and rendering is slow, you'll get a dismount and then mount again, and that will leave a visible flashing effect.

**Comment by wuweiweiwu** [comment] 2018-05-15 08:49
Hi @sslgeorge @vjeranc Can you guys open a new issue and link back to this one? And also provide a minimum reproduction in a codesandbox?

That'll be great!

**Comment by HebaruSan** [comment] 2018-05-27 17:27
In case this helps others searching for this issue:

I was having this same problem for a while; the cause was that the `style` parameter of my `rowRenderer` was not being applied to the list elements. In my specific case it was a bit tricky because it _looked_ like it was being applied, but I had created a custom list item React component that was not applying `this.props.style` to its root element. The problem was solved when I fixed this.

Main loop:

```
<AutoSizer>{
    ({ height, width }) => {
        return (
            <List
                deferredMeasurementCache={this.measurerCache}
                height={height}
                width={width}
                rowCount={modules.length}
                rowHeight={80}
                rowRenderer={this.mkRow}
                />
        );
    }
}</AutoSizer>
```

Row renderer:

```
mkRow({ key, index, isScrolling, isVisible, style, parent }) {
    const { errorOpen, errorTitle, errorMessage         } = this.state;
    const { classes,   className,  Search, ModuleFilter } = this.props;

    const modules = this.state[ModuleFilter];
    const module  = modules[index];

    return (
        <CellMeasurer cache={this.measurerCache} key={module.Identifier} parent={parent} rowIndex={index}>
            <ModulesListItem style={style} module={module} Search={Search} />
        </CellMeasurer>
    );
}
```

List item's `render()` broken:

```
<ListItem className={classes.root} component="div" ContainerComponent="div">
```

List item's `render()` fixed:

```
<ListItem style={this.props.style} className={classes.root} component="div" ContainerComponent="div">
```

Thanks to the team members for this nice component; it's really quite impressive once it's working!

**Comment by laura-brouckman** [comment] 2019-02-08 23:37
@bvaughn I am also seeing this issue, with a very basic `List`. 
See the output here https://codesandbox.io/s/1r0lnro7y4

Or look at the code here
```
import * as React from 'react';
import { List } from react-virtualized;

const TEST_HEIGHT = 25;
const list = [
  'item 1',
  'item 2',
  'item 3',
  'item 4',
  'item 5',
  'item 6',
  'item 7',
  'item 8',
  'item 9',
  'item 10',
];

class BrokenList extends React.Component {
  render() {
    return (
      <List
        width={200}
        height={5 * TEST_HEIGHT}
        rowHeight={TEST_HEIGHT}
        rowCount={list.length}
        rowRenderer={({ index, key }) => {
          return (
            <div key={key} style={{height: TEST_HEIGHT}}>
              {list[index]}
            </div>
          )
        }}
      />
    )
  }
}
```
The output:
![badscroll](https://user-images.githubusercontent.com/43153741/52511833-adb6ee80-2bb6-11e9-9df2-12b6cfeac4a9.gif)

If it is important, the browser is Chrome 71.0.3578.98 on MacOS High Sierra 

I've read through the responses above and none seem to explain this issue. This (to me) seems to be the most minimal `List`. Any guidance on this would be appreciated. Thanks!

**Comment by 9996b6999** [comment] 2024-02-18 21:21
Sorry guys, but in my case applying the style doesn't help. I've been fighting this problem several days already. Actually tried a lot of things. And for sure applying this style to the raw doesn't work. I noticed a little different thing... that looks like it rather works than not in my case... At least in my case, it improves rendering and It flickers less.
