### ISSUE TITLE
Problems with scrolling

### ISSUE THREAD

**Issue by yuristrelets** [bvaughn/react-virtualized#822] opened 2017-09-25 15:53 UTC
I am trying to use `List`, something like this
```
<AutoSizer>
  {({ height, width }) => (
    <List
      width={width}
      height={height}
      rowHeight={48}
      rowRenderer={({ index }) => (
        <div style={{ height: 48 }} key={index}>Item {index}</div>
      )}
      rowCount={rows.size}
    />
  )}
</AutoSizer>
```
But instead of smoothly scrolling I get terribly jerky on chrome 61.0.3163.100 https://www.screencast.com/t/I7yRYcu71
on FF 55.0.3 I had empty space at the end https://www.screencast.com/t/JOT1Bswz

Without `AutoSizer` the problem doesn't disappear. 
I'm using the latest versions of react and react-virtualized.

What am I doing wrong? 
Who faced such a problem?

**Comment by christiantinauer** [comment] 2017-09-25 18:07
Same problem here. Introduced with 9.10.0. Downgrading to 9.9.0 fixes the problem.

**Comment by istarkov** [comment] 2017-09-25 21:43
Same here

**Comment by yuristrelets** [comment] 2017-09-26 08:35
Unfortunetely, even rolling back to version 9.9.0, and then 9.0.0 and 8.11.4, didn't solve the problem. I used version 7 for a long time and wanted to try the latest version in the new project. On version 7 there is no such problem. I have no ideas.

**Comment by TrySound** [comment] 2017-09-26 08:46
@yuristrelets That's because you should pass style and key (not index) props to your div
```js
      rowRenderer={({ style, key, index }) => (
        <div style={{ height: 48 }} style={style} key={key}>Item {index}</div>
      )}
```

**Comment by yuristrelets** [comment] 2017-09-26 09:34
@TrySound You're right! My fault, I didn't see that it's necessary to pass `style` ad `key`. Downgrading to version 9.9.0 and changing `rowRenderer` solved the problem. Thank you!

**Comment by mtycvy** [comment] 2017-09-27 12:39
I have experienced this problem with v9.10 downgrading to 9.9.0 fixed the issue.

**Comment by bradbirnbaum** [comment] 2017-09-27 19:10
We are seeing the same issue on 9.10.1 as well.

**Comment by istarkov** [comment] 2017-09-27 20:24
Guys here is the fix https://github.com/bvaughn/react-virtualized/pull/825

**Comment by bvaughn** [comment] 2017-10-14 18:13
Fixed by #825

Will be released momentarily as 9.11

**Closed by bvaughn** 2017-10-14 18:13 UTC

**Comment by w10036w** [comment] 2018-07-17 19:07
react-virtualized ^9.20.1 still has this issue.
After add some dummy style it is resolved. 
Please reopen this issue or at least mark "style" as a compulsory parameter to avoid this.

env: 
mac 10.13.4
chrome 67.0.3396
node 9.2.0
yarn 1.7.0

**Comment by nileshpawar-xento** [comment] 2018-12-14 11:06
Facing the same issue in the react-virtualized ^9.21.0 also :(

My code's snap like:
<List 
  width=800  height=50  rowHeight=600
  rowRenderer={
  ({ index, style, key, ...rest }) => {
    return (
      <Component
        key={key}
        style={style}
        {...this.props.items[index]}   />
       )
     }
    }
    rowCount={items.length}
 />

Env:
Windows10
yarn version v1.12.3
Chrome Version 71.0.3578.98

Please suggest me if I'm missing anything here.

**Comment by edgars-sirokovs** [comment] 2019-01-29 15:08
Having a similar issue on `9.21.0`. Using `WindowScroller` and `AutoSizer`. When the list has no entries scrolling starts to jump once top of the list is at window top.

Screen recording:
![scroll-junk](https://user-images.githubusercontent.com/4445243/51917266-dc2f0f80-23e7-11e9-9538-e9a7776520cb.gif)

Code:
```jsx
        <WindowScroller>
          {({height, isScrolling, onChildScroll, scrollTop}) => (
            <AutoSizer disableHeight>
              {({width}) => (
                <List
                  ref={this.setListRef}
                  autoHeight
                  estimatedRowSize={ROW_HEIGHT}
                  height={height}
                  isScrolling={isScrolling}
                  noRowsRenderer={this.noRowsRenderer}
                  onScroll={onChildScroll}
                  overscanRowCount={2}
                  rowCount={productsListRows.length}
                  rowHeight={this.getRowHeight}
                  rowRenderer={this.rowRenderer}
                  scrollTop={scrollTop}
                  width={width}
                />
              )}
            </AutoSizer>
          )}
```

**Comment by jaxxreal** [comment] 2019-07-04 15:33
I have the same issue as @yuristrelets. `react-virtualized@9.21.1` on Chrome 75.0.3770.100. Any news? Taking into account last 3 unresponded comments.

**Comment by Artur93gev** [comment] 2019-08-31 19:32
Same problem

**Comment by sebastian-schlecht** [comment] 2019-09-10 20:08
Same here, Chrome Version 76.0.3809.132 (Official Build) (64-bit). Safari works fine. 
`react-virtualized@9.21.1`

**Comment by smit1625** [comment] 2020-05-05 15:30
Adding one more to the pile. I am still seeing this problem in Chrome on `9.21.2`.

**Comment by ap-in-git** [comment] 2020-06-24 15:19
I used this component and modified it
https://github.com/bvaughn/react-virtualized/blob/master/source/Table/defaultRowRenderer.js

**Comment by colecorrente** [comment] 2020-08-03 18:00
Was experiencing this on Chrome with `9.21.2`.
Adding `style={{width: "100%", height: "100%"}}` to the `<AutoSizer>` component itself has fixed this for me weirdly.

**Comment by chesaman12** [comment] 2020-11-13 17:50
I'm experiencing this issue with the AutoSizer and virtualized table. Sadly style tags haven't helped me and I'm experiencing a very jerky table. Has anyone figured out more about whats going on here?

**Comment by LiranCohen** [comment] 2020-12-05 12:08
In case anyone is having this issue, passing the style down to whatever actual div is rendered for the row is what fixed this for me.

I had originally passed down the style property to the row component, but I didn't use that property anywhere in the row.
I then passed it down to the base row component which passed the style to the actual div creating the row.

Hope this helps anyone else.

**Comment by noumanaltaf** [comment] 2022-05-19 14:56
facing same issue, using "react-virtualized": "^9.22.3"

**Comment by FoSuCloud** [comment] 2022-06-29 11:58
> 
I also

**Comment by syafilm** [comment] 2022-07-13 15:41
I also face the same issue, can anyone help?

**Comment by gewalttat** [comment] 2023-01-26 15:47
still reproducing

**Comment by riddhi-24** [comment] 2024-06-14 05:44
@bvaughn Can you please update if this issue is fixed with any updates, as we're facing the same issue where scrolling from top to bottom, screen is getting blank for fewer milliseconds distorting the user experience.

**Comment by vijay-t13** [comment] 2024-08-29 12:29
any update on this??
