### ISSUE TITLE
Table row is padded to the right with 15px that enables superfluous scrolling 

### ISSUE THREAD

**Issue by gajus** [bvaughn/react-virtualized#274] opened 2016-06-14 15:24 UTC
This is visible in the demo page of the FlexTable and VirtualScroll, https://bvaughn.github.io/react-virtualized/.

Using mouse middle button (or touchpad scroll gesture), I am able to scroll table to the right. Furthermore, only the body adds this padding. Therefore, scrolling body misaligns header with the body.

**Comment by bvaughn** [comment] 2016-06-14 16:23
I can't reproduce what you're describing in Chrome, Firefox, or Safari- either with scrollbars on auto or always-on.

**Comment by gajus** [comment] 2016-06-15 08:37
Interesting. Here is a FlexTable demo scrolled to the right.

![15-06-2016 09-35-16](https://cloud.githubusercontent.com/assets/973543/16073158/85968fee-32dc-11e6-9df7-3afe94254d50.png)

Here is information about my browser http://whatsmybrowser.org/b/MFX4DV2

I will see if I can replicate the same behavior when I get back home.

Note, this affects not only the demo. The same problem applies when trying to implement `react-virtualized` in our app.

**Comment by bvaughn** [comment] 2016-06-15 14:43
I'm using Chrome 51.0.2704.84 on OS X. I also just gave Firefox 44, Chrome 48, and IE10 a spin on Windows 7 in VirtualBox. I was unable to reproduce what you've described there either.

> Also note the outline. Probably best to remove it from the demo/ default css.
The outline is the browser's default focus highlight. If you want to disable it you can either set the `tabIndex` equal to -1 (to disable focus entirely) or you could override via a custom CSS class or style. I plan to leave it in place by default since it is a usability aid.

I'm going to close this issue for no since I'm not able to reproduce. Doing this helps me keep on top of issues so the issues board doesn't get too cluttered and hard to manage. I'll still see comments on the issue though so we can still exchange information about it.

**Closed by bvaughn** 2016-06-15 14:43 UTC
Labels: bug: unconfirmed, more info needed

**Comment by sndsgn** [comment] 2018-08-27 03:37
Experiencing this issue "react-virtualized": "^9.20.1". Chrome shows the below and this padding-right value is not in my style sheets.
`<div class="ReactVirtualized__Table__headerRow myclassname__2H78B" role="row" style="height: 30px; overflow: hidden; padding-right: 15px; width: 960px;">`

**Comment by raedbenz** [comment] 2018-12-07 16:19
I managed to disable it on Chrome by setting a class for grid and make outline: none

gridClassName='grid'
.grid {
    outline: none;
}

.grid:focus {
    outline: none;
}
