### ISSUE TITLE
WindowScroller scrolling issue

### ISSUE THREAD

**Issue by monopieces** [bvaughn/react-virtualized#1041] opened 2018-03-08 08:51 UTC
We have a production page including several charts and a react-virtualized table, charts are in the upper of table, but display later.

There will be an issue when the page mount with complete table, user start scrolling the page, and then chart finish fetching data and show, the scrolling table will be cut off with a couple of blank rows.

Here is the example:
* CodePen: https://codepen.io/pieces/pen/xWKyZE
* Screen capture: 
![error](https://user-images.githubusercontent.com/1772355/37140914-4824fa70-22ee-11e8-8d79-ba88b8e6b8c2.gif)

Please me some ideas how to handle that, Thanks!

**Comment by monopieces** [comment] 2018-03-08 10:12
After checking the code, I guess the `updatePosition()`  in WindowScroller.js `componentWillReceiveProps` function may not be triggered in this situation. Because page grows due to other components, `_positionFromTop` still store the old value without any updates.

```js
// WindowScroller.js
componentWillReceiveProps(nextProps: Props) {
    const scrollElement = this.props.scrollElement;
    const nextScrollElement = nextProps.scrollElement;

    if (
      scrollElement !== nextScrollElement &&
      scrollElement &&
      nextScrollElement
    ) {
      this.updatePosition(nextScrollElement, nextProps);

      unregisterScrollListener(this, scrollElement);
      registerScrollListener(this, nextScrollElement);

      this._unregisterResizeListener(scrollElement);
      this._registerResizeListener(nextScrollElement);
    }
  }
```

**Comment by karatechops** [comment] 2018-03-13 19:01
Hey @monopieces, this looks to be a duplicate of #671. I've updated [your codepen](https://codepen.io/karatechops/pen/OvMpbq?editors=0010) to provide an example for manually calling `updatePosition`. You can find more information regarding WindowScroller in [the doc](https://github.com/bvaughn/react-virtualized/blob/master/docs/WindowScroller.md).

**Comment by monopieces** [comment] 2018-03-15 03:00
Cool!! that solves my problem, thanks man!

**Closed** 2018-03-15 09:17 UTC
