### ISSUE TITLE
Bug with chat recipe (CellMeasurer + VirtualScroll)

### ISSUE THREAD

**Issue by zsherman** [bvaughn/react-virtualized#338] opened 2016-08-05 21:52 UTC
I know that this use case may not be 100% supported at the moment, but I noticed that as the amount of lines a `CellMeasurer` wrapped component has to render increases, the more likely it is to improperly calculate item heights.

For example resizing this [recipe page](https://rawgit.com/bvaughn/react-virtualized/master/playground/chat.html) to < 500px results in improper chat box heights:

<img width="401" alt="screenshot 2016-08-05 17 49 02" src="https://cloud.githubusercontent.com/assets/1152279/17451487/3e9f578e-5b35-11e6-8fae-9a7aadf9e639.png">

**Comment by bvaughn** [comment] 2016-08-05 22:07
Hm... I think it's actually a resize-event bug. If you resize that recipe page to < 500px and then reload it, everything renders correctly. But if you start large and resize the bug- things don't update to account for the smaller size.

I'll look into it.

**Comment by zsherman** [comment] 2016-08-05 22:08
thanks @bvaughn! I also noticed something similar in my app when the number of lines gets excessively large. I'll try to put together an example to demo.

**Comment by bvaughn** [comment] 2016-08-05 22:13
If you beat me to a fix, let me know ;)

**Comment by bvaughn** [comment] 2016-08-07 01:37
Debugged this for a bit before realizing the problem here.

The hidden div used for measuring is _slightly_ wider than the one used in the list. Occasionally this results in a case where text wraps more within the list than it does in the measuring cell. The difference is equal to the size of the left + right border.

You can actually see this by inspecting the `.Grid__innerScrollContainer` component and looking at its `style.width` compared to the `clientWidth` of any of the `.Grid__cell`s within it.

**Comment by bvaughn** [comment] 2016-08-07 01:43
I'm not sure of a super clean way around this, off the top of my head. :)

There's an easy fix for the demo, which is... not to use `border-box`. A more generalized fix would be to not set a `border` on a `Grid` directly, but to set it on the `Grid`'s parent.

But neither of these are very satisfying.

**Comment by zsherman** [comment] 2016-08-07 01:59
@bvaughn nice catch.

**Comment by bvaughn** [comment] 2016-08-07 03:38
Fixed (in the playground test harness) via a27144d.

Updated the [`CellMeasurer` docs](https://github.com/bvaughn/react-virtualized/blob/master/docs/CellMeasurer.md) to call out this potential edge-case.

Thanks for the bug report. :)

**Comment by iwano** [comment] 2016-09-19 13:14
Im experiencing this exact same issue and im on v8. At the beginning I thought it had to do with OSX scrollbars settings (sometimes appearing and taking space out of the innerScrollContainer), but then I checked the chat playground example (also v8) to see if I was doing something wrong and realized is happening there too on both initial load and resize (no matter what the scrollbar settings are).

<img width="399" alt="screen shot 2016-09-19 at 9 01 09 am" src="https://cloud.githubusercontent.com/assets/1461614/18633037/5d77e064-7e48-11e6-8835-3b7f416b7f6f.png">
<img width="399" alt="screen shot 2016-09-19 at 8 58 39 am" src="https://cloud.githubusercontent.com/assets/1461614/18633036/5d749e7c-7e48-11e6-9c02-8c3a839b09c6.png">

I can also confirm is not a v8 specific issue, I experienced the exact same on 7.24.3

**Comment by iwano** [comment] 2016-09-19 16:36
Funny, I was able to reproduce it with the default option as well **but only in the playground example**. In an implementation I have in a project only breaks with the scrollbars set to **always**, but I may have done something wrong when testing the playground.

One annoying issue is that even if you have the "When scrolling" option set, sometimes chrome will show the scrollbars at all times anyway for some reason.. is there even a way of knowing if the scrollbar will be rendered? there could be a padding on the grid to leave space for the scrollbars at all times and dont take it into consideration but this may not be a pretty nor cross-browser solution

**Comment by bvaughn** [comment] 2016-09-19 16:42
> One annoying issue is that even if you have the "When scrolling" option set, sometimes chrome will show the scrollbars at all times anyway for some reason..

I've noticed that recently with Chrome as well.

> is there even a way of knowing if the scrollbar will be rendered?

I use a combination of [this library](https://github.com/react-bootstrap/dom-helpers/blob/master/src/util/scrollbarSize.js) and [this code in `Grid`](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.js#L500-L504). I don't know of a better approach.

**Comment by bvaughn** [comment] 2016-09-19 18:28
By the way, I'm closing this issue in favor of #401 (since this is kind of a separate, albeit related, issue from what was originally reported). Follow along there. 😄

**Closed by bvaughn** 2016-09-19 18:28 UTC
Labels: bug: unconfirmed
