### ISSUE TITLE
AutoSizer doesn't show List after zooming out

### ISSUE THREAD

**Issue by ethankong113** [bvaughn/react-virtualized#849] opened 2017-10-17 22:13 UTC
I have this weird bug when I use AutoSizer and List together, along with display flex applied on a parent container. Pseduocode below:

&lt;div style={{display: 'flex'}}&gt;
  &lt;div style={{flex-grow: '1'}}&gt;
    &lt;AutoSize&gt;
      {({width, height}) => &lt;List width={width} height={height} /&gt;}
    &lt;/AutoSize&gt;
  &lt;/div&gt;
&lt;/div&gt;

When I try to zoom out to 80%, the list disappears. If I try to drag the browser to enlarge it vertically, it reappears. Upon investigation, the rowRenderer function doesn't run when I zoom out. I couldn't write code to reproduce it because it seems to appear on some laptops and not others. (For example, I could reproduce it with a different screen size.)

This is a really weird bug and I suspect it has something to do with certain browsers only. Do you know anything that might cause this problem or anyone opened a similar issue before?

**Comment by bvaughn** [comment] 2017-10-21 16:34
Sorry, but I don't know what would cause this. It could be a browser bug, maybe a flexbox quirk. I don't think there's any action I can take on this though with this little amount of information unfortunately.

I think I'm going to close this for now since I don't think there's any action I can take on it, but we can still talk about it via comments and I can re-open if more info is provided and it looks like something caused by, or avoidable by, react-virtualized. 👍

**Closed by bvaughn** 2017-10-21 16:34 UTC
