### ISSUE TITLE
MS Edge Support

### ISSUE THREAD

**Issue by mdekrey** [bvaughn/react-virtualized#359] opened 2016-08-24 21:19 UTC
When testing with MS Edge (38.14393.0.0) on the react-virtualized demo page (https://bvaughn.github.io/react-virtualized/) with a large number of items (100,000), scrolling to the bottom using the scrollbar does not display all elements in this case.

In addition, it looks like sometimes when scolling is done via the mouse wheel, an unexpected amount of distance is scrolled: it can scroll a lot or only a little. (I haven't found the connection for the amount it actually scrolls, but have on occasion seen it flicker, only to appear to have not scrolled.)

**Comment by bvaughn** [comment] 2016-08-24 21:22
TBH I've only tested RV in IE 9, 10, and 11. I'll grab a VM from modern.ie with Edge in it and try to take a look at some point.

If you're developing on Windows and can more easily repro this, I'd appreciate any insights or debugging you're able to do (or even a PR). :)

**Comment by mdekrey** [comment] 2016-08-24 21:24
I'm actively working on this from my end; if I can track it down precisely, I'll definitely do a PR. 

I'm having different behaviors in my own environment versus the demo at the moment, and I'm not sure why, but will be working on it more this week!

**Comment by bvaughn** [comment] 2016-08-24 21:25
Much appreciated. 😄

**Comment by bvaughn** [comment] 2016-08-27 18:52
Ah ha! So I just got around to giving this a spin on a Virtual Box VM with Edge and I'm pretty sure the issue is that IE doesn't support a `scrollHeight` tall enough for 100,000 rows at 50 pixels per row. Looks like Edge is topping out with a `scrollTop` of ~1.5M pixels.

The [MS docs](https://msdn.microsoft.com/en-us/library/windows/apps/hh780138.aspx) mention this behavior without giving a lot of information:

> This property's value equals the current vertical offset of the content within the scrollable range. Although you can set this property to any value, **if you assign a value less than 0, the property is set to 0. If you assign a value greater than the maximum value, the property is set to the maximum value**.

I attempted to work around this with [`ScalingCellSizeAndPositionManager`](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/utils/ScalingCellSizeAndPositionManager.js) but it seems I didn't pick a value low enough for the often-disappointing IE family. 😏 I've just confirmed that lowering the threshold from 10M to 1.5M fixes the problem for Edge.

I kind of hate doing this but... maybe it's the best option since Edge support is important.

#### Related issues:
* bvaughn/react-virtualized#193: `VirtualScroll` fails to render items correctly for over 559239 items
* bvaughn/react-virtualized#304: Imprecise scrollTop value when scrolling
* facebook/fixed-data-table#251: Data table breaks down with large ordinate parameter to translate3d

**Comment by bvaughn** [comment] 2016-08-27 19:01
@mdekrey: Just published version 7.21.1 with the lowered threshold. 100,000 rows looks fine for me in Edge (in a VM). Give it a spin on the demo site and let me know if it's working better for you too.

Going to close this issue for now because I _think_ it's behavior well. Please let me know if there are additional issues though and I can re-open it. 😄

**Closed by bvaughn** 2016-08-27 19:01 UTC
Labels: bug: unconfirmed
